import type { BibleRef } from "@/lib/atlas-shared";

export type Realm = "unido" | "israel" | "juda";

export const REALM_META: Record<Realm, { label: string; emoji: string; description: string }> = {
  unido: {
    label: "Reino Unido",
    emoji: "👑",
    description: "As doze tribos sob um único rei, de Saul a Salomão.",
  },
  israel: {
    label: "Reino de Israel (Norte)",
    emoji: "🏔️",
    description: "As dez tribos do norte, com capital em Samaria, até a queda diante da Assíria.",
  },
  juda: {
    label: "Reino de Judá (Sul)",
    emoji: "🏛️",
    description: "Judá e Benjamim, com capital em Jerusalém, até o exílio babilônico.",
  },
};

export type BibleKing = {
  id: string;
  name: string;
  realm: Realm;
  order: number;
  /** duração/período conforme o texto bíblico; vazio quando não informado */
  period: string;
  /** "bom", "misto", "mau" conforme a avaliação do próprio texto bíblico */
  verdict: "bom" | "misto" | "mau" | "nao-avaliado";
  summary: string;
  history: string;
  events: string[];
  godRelation: string;
  people: string[];
  places: string[];
  refs: BibleRef[];
  curiosities: string[];
};

const r = (book: string, chapter: number, label: string): BibleRef => ({ book, chapter, label });

export const VERDICT_META: Record<BibleKing["verdict"], { label: string; emoji: string }> = {
  bom: { label: "Fez o que era reto aos olhos do Senhor", emoji: "🙏" },
  misto: { label: "Começo fiel, fim marcado por falhas", emoji: "⚖️" },
  mau: { label: "Fez o que era mau aos olhos do Senhor", emoji: "🌑" },
  "nao-avaliado": { label: "O texto não registra avaliação", emoji: "•" },
};

export const BIBLE_KINGS: BibleKing[] = [
  /* ------------------------------- Reino Unido ------------------------------ */
  {
    id: "saul",
    name: "Saul",
    realm: "unido",
    order: 1,
    period: "Primeiro rei de Israel",
    verdict: "misto",
    summary: "O primeiro rei, escolhido quando o povo pediu um rei como as outras nações.",
    history:
      "Da tribo de Benjamim, foi ungido por Samuel e aclamado em Mispa. Venceu batalhas importantes, mas foi rejeitado como rei por desobedecer à palavra do Senhor.",
    events: [
      "Unção por Samuel e confirmação diante do povo.",
      "Vitória sobre os amonitas em Jabes-Gileade.",
      "Sacrifício indevido em Gilgal e desobediência quanto a Amaleque.",
      "Perseguição a Davi durante anos.",
      "Morte no monte Gilboa, junto com seus filhos.",
    ],
    godRelation:
      "O texto registra que Saul foi rejeitado por não obedecer à palavra do Senhor, e que o Espírito se retirou dele.",
    people: ["Samuel", "Jônatas", "Davi", "Mical", "Abner"],
    places: ["Gibeá", "Mispa", "Gilgal", "Monte Gilboa"],
    refs: [r("1sm", 9, "1 Samuel 9"), r("1sm", 15, "1 Samuel 15"), r("1sm", 31, "1 Samuel 31")],
    curiosities: ["Jônatas, filho de Saul, foi o grande amigo de Davi."],
  },
  {
    id: "davi",
    name: "Davi",
    realm: "unido",
    order: 2,
    period: "Quarenta anos: sete em Hebrom e trinta e três em Jerusalém",
    verdict: "bom",
    summary: "O pastor de Belém que se tornou rei, guerreiro, músico e autor de muitos salmos.",
    history:
      "Ungido ainda jovem por Samuel, ficou conhecido pela vitória sobre Golias. Reinou primeiro sobre Judá em Hebrom e depois sobre todo o Israel, fazendo de Jerusalém a capital.",
    events: [
      "Vitória sobre Golias no vale de Elá.",
      "Fuga e anos de perseguição por Saul.",
      "Conquista de Jerusalém e transporte da arca.",
      "Aliança de Deus com a sua casa.",
      "Pecado com Bate-Seba, confronto do profeta Natã e arrependimento.",
      "Rebelião de Absalão.",
    ],
    godRelation:
      "Chamado de homem segundo o coração de Deus; falhou gravemente, confessou o pecado e recebeu perdão, mas enfrentou as consequências.",
    people: ["Samuel", "Jônatas", "Joabe", "Natã", "Bate-Seba", "Absalão", "Salomão"],
    places: ["Belém", "Hebrom", "Jerusalém", "En-Gedi"],
    refs: [r("1sm", 16, "1 Samuel 16"), r("1sm", 17, "1 Samuel 17"), r("2sm", 7, "2 Samuel 7"), r("sl", 51, "Salmos 51")],
    curiosities: ["Muitos salmos trazem o nome de Davi no título."],
  },
  {
    id: "salomao",
    name: "Salomão",
    realm: "unido",
    order: 3,
    period: "Quarenta anos",
    verdict: "misto",
    summary: "O rei que pediu sabedoria e construiu o Templo, mas cujo coração se desviou no fim da vida.",
    history:
      "Filho de Davi e Bate-Seba, herdou um reino unificado e próspero. Construiu o Templo em Jerusalém e ficou conhecido pela sabedoria e pela riqueza.",
    events: [
      "Pedido de um coração sábio em Gibeom.",
      "Julgamento entre as duas mulheres.",
      "Construção e dedicação do Templo.",
      "Visita da rainha de Sabá.",
      "Casamentos estrangeiros e culto a outros deuses no fim da vida.",
    ],
    godRelation:
      "Deus lhe deu sabedoria e riqueza; o texto afirma que, na velhice, suas mulheres desviaram o seu coração, e por isso o reino seria dividido.",
    people: ["Davi", "Bate-Seba", "Natã", "Hirão de Tiro", "Rainha de Sabá", "Roboão"],
    places: ["Jerusalém", "Gibeom", "Meguido"],
    refs: [r("1rs", 3, "1 Reis 3"), r("1rs", 8, "1 Reis 8"), r("1rs", 11, "1 Reis 11"), r("pv", 1, "Provérbios 1")],
    curiosities: ["A tradição liga a ele Provérbios, Eclesiastes e Cânticos."],
  },

  /* ---------------------------- Reino de Israel ---------------------------- */
  {
    id: "jeroboao-i",
    name: "Jeroboão I",
    realm: "israel",
    order: 1,
    period: "Vinte e dois anos",
    verdict: "mau",
    summary: "O primeiro rei do Norte, que instituiu os bezerros de ouro em Betel e Dã.",
    history: "Servo de Salomão, liderou a separação das dez tribos após a recusa de Roboão em aliviar a carga do povo.",
    events: ["Divisão do reino.", "Bezerros de ouro em Betel e Dã.", "Confronto com o homem de Deus junto ao altar."],
    godRelation: "É lembrado repetidamente como aquele que 'fez Israel pecar'.",
    people: ["Roboão", "Aías, o silonita", "Salomão"],
    places: ["Siquém", "Betel", "Dã", "Tirza"],
    refs: [r("1rs", 12, "1 Reis 12"), r("1rs", 13, "1 Reis 13")],
    curiosities: ["Vários reis posteriores são comparados a ele nas avaliações do texto."],
  },
  { id: "nadabe", name: "Nadabe", realm: "israel", order: 2, period: "Dois anos", verdict: "mau",
    summary: "Filho de Jeroboão, morto por Baasa durante um cerco.", history: "Seu reinado curto terminou com o fim da casa de Jeroboão.",
    events: ["Cerco a Gibetom.", "Conspiração de Baasa."], godRelation: "O texto diz que andou no caminho de seu pai.",
    people: ["Jeroboão I", "Baasa"], places: ["Gibetom"], refs: [r("1rs", 15, "1 Reis 15")], curiosities: [] },
  { id: "baasa", name: "Baasa", realm: "israel", order: 3, period: "Vinte e quatro anos", verdict: "mau",
    summary: "Tomou o trono eliminando a casa de Jeroboão.", history: "Reinou em Tirza e guerreou contra Asa, rei de Judá.",
    events: ["Extermínio da casa de Jeroboão.", "Fortificação de Ramá.", "Profecia de Jeú, filho de Hanani."],
    godRelation: "Foi advertido por profeta por seguir o caminho de Jeroboão.", people: ["Asa", "Jeú, filho de Hanani"],
    places: ["Tirza", "Ramá"], refs: [r("1rs", 15, "1 Reis 15"), r("1rs", 16, "1 Reis 16")], curiosities: [] },
  { id: "ela", name: "Elá", realm: "israel", order: 4, period: "Dois anos", verdict: "mau",
    summary: "Filho de Baasa, morto por Zinri.", history: "Foi assassinado enquanto bebia em Tirza.",
    events: ["Conspiração de Zinri."], godRelation: "O texto o inclui entre os que fizeram o mal.",
    people: ["Baasa", "Zinri"], places: ["Tirza"], refs: [r("1rs", 16, "1 Reis 16")], curiosities: [] },
  { id: "zinri", name: "Zinri", realm: "israel", order: 5, period: "Sete dias", verdict: "mau",
    summary: "O reinado mais curto registrado no Reino do Norte.", history: "Cercado em Tirza, morreu no incêndio do palácio.",
    events: ["Golpe contra Elá.", "Cerco de Onri."], godRelation: "O texto o avalia negativamente.",
    people: ["Elá", "Onri"], places: ["Tirza"], refs: [r("1rs", 16, "1 Reis 16")], curiosities: ["Reinou apenas sete dias."] },
  { id: "onri", name: "Onri", realm: "israel", order: 6, period: "Doze anos", verdict: "mau",
    summary: "Fundador de Samaria e de uma dinastia influente.", history: "Comprou o monte de Semer e ali edificou a nova capital.",
    events: ["Disputa com Tibni.", "Fundação de Samaria."], godRelation: "O texto diz que fez pior que todos os que houve antes dele.",
    people: ["Tibni", "Acabe"], places: ["Samaria", "Tirza"], refs: [r("1rs", 16, "1 Reis 16")], curiosities: [] },
  {
    id: "acabe",
    name: "Acabe",
    realm: "israel",
    order: 7,
    period: "Vinte e dois anos",
    verdict: "mau",
    summary: "Rei casado com Jezabel, contemporâneo do profeta Elias.",
    history: "Promoveu o culto a Baal em Israel e enfrentou repetidas advertências proféticas.",
    events: [
      "Casamento com Jezabel e altar a Baal em Samaria.",
      "Seca anunciada por Elias.",
      "Desafio do monte Carmelo.",
      "Episódio da vinha de Nabote.",
      "Morte em batalha em Ramote-Gileade.",
    ],
    godRelation: "Foi confrontado por Elias; humilhou-se depois do caso de Nabote e o juízo anunciado foi adiado.",
    people: ["Jezabel", "Elias", "Micaías", "Nabote", "Josafá"],
    places: ["Samaria", "Monte Carmelo", "Jezreel", "Ramote-Gileade"],
    refs: [r("1rs", 16, "1 Reis 16"), r("1rs", 18, "1 Reis 18"), r("1rs", 21, "1 Reis 21"), r("1rs", 22, "1 Reis 22")],
    curiosities: ["A vinha de Nabote ficava ao lado do palácio de Jezreel."],
  },
  { id: "acazias-israel", name: "Acazias (Israel)", realm: "israel", order: 8, period: "Dois anos", verdict: "mau",
    summary: "Filho de Acabe, morreu após consultar Baal-Zebube.", history: "Caiu de uma janela e enviou mensageiros a um deus estrangeiro em vez de buscar o Senhor.",
    events: ["Consulta a Baal-Zebube.", "Palavra de Elias sobre sua morte."], godRelation: "Foi repreendido por buscar outro deus.",
    people: ["Acabe", "Jezabel", "Elias"], places: ["Samaria", "Ecrom"], refs: [r("2rs", 1, "2 Reis 1")], curiosities: [] },
  { id: "jorao-israel", name: "Jorão (Israel)", realm: "israel", order: 9, period: "Doze anos", verdict: "mau",
    summary: "Último rei da casa de Acabe, morto por Jeú.", history: "Reinou durante boa parte do ministério de Eliseu.",
    events: ["Guerra contra Moabe.", "Cerco de Samaria e livramento anunciado por Eliseu.", "Morte às mãos de Jeú."],
    godRelation: "Removeu a estátua de Baal, mas manteve os pecados de Jeroboão.", people: ["Eliseu", "Jeú", "Naamã"],
    places: ["Samaria", "Jezreel"], refs: [r("2rs", 3, "2 Reis 3"), r("2rs", 6, "2 Reis 6"), r("2rs", 9, "2 Reis 9")], curiosities: [] },
  { id: "jeu", name: "Jeú", realm: "israel", order: 10, period: "Vinte e oito anos", verdict: "misto",
    summary: "Ungido para acabar com a casa de Acabe e com o culto a Baal.", history: "Foi ungido por ordem de Eliseu e executou juízo sobre a dinastia de Onri.",
    events: ["Unção por um discípulo dos profetas.", "Fim da casa de Acabe.", "Destruição do templo de Baal em Samaria."],
    godRelation: "Cumpriu o que Deus ordenou contra a casa de Acabe, mas não abandonou os bezerros de ouro.",
    people: ["Eliseu", "Jezabel", "Jorão", "Jonadabe"], places: ["Ramote-Gileade", "Jezreel", "Samaria"],
    refs: [r("2rs", 9, "2 Reis 9"), r("2rs", 10, "2 Reis 10")], curiosities: [] },
  { id: "jeoacaz-israel", name: "Jeoacaz (Israel)", realm: "israel", order: 11, period: "Dezessete anos", verdict: "mau",
    summary: "Reinou em tempo de forte pressão da Síria.", history: "O exército de Israel foi reduzido drasticamente durante o seu reinado.",
    events: ["Opressão de Hazael.", "Clamor ao Senhor e alívio temporário."], godRelation: "Buscou o Senhor na aflição e recebeu socorro.",
    people: ["Jeú", "Hazael"], places: ["Samaria"], refs: [r("2rs", 13, "2 Reis 13")], curiosities: [] },
  { id: "jeoas-israel", name: "Jeoás (Israel)", realm: "israel", order: 12, period: "Dezesseis anos", verdict: "mau",
    summary: "Visitou Eliseu no leito de morte e venceu a Síria três vezes.", history: "Recuperou cidades perdidas para os sírios.",
    events: ["Encontro com Eliseu e o sinal das flechas.", "Vitórias sobre a Síria.", "Conflito com Amazias de Judá."],
    godRelation: "Manteve os pecados de Jeroboão, ainda que Deus tenha concedido vitórias.",
    people: ["Eliseu", "Amazias"], places: ["Samaria", "Bete-Semes"], refs: [r("2rs", 13, "2 Reis 13"), r("2rs", 14, "2 Reis 14")], curiosities: [] },
  { id: "jeroboao-ii", name: "Jeroboão II", realm: "israel", order: 13, period: "Quarenta e um anos", verdict: "mau",
    summary: "Reinado longo e próspero, contemporâneo de Amós e Oseias.", history: "Restaurou as fronteiras de Israel, num tempo de riqueza e de forte denúncia profética contra a injustiça.",
    events: ["Expansão das fronteiras.", "Ministério de Amós, Oseias e Jonas."], godRelation: "O texto o avalia negativamente, apesar da prosperidade.",
    people: ["Amós", "Oseias", "Jonas"], places: ["Samaria", "Betel"], refs: [r("2rs", 14, "2 Reis 14"), r("am", 7, "Amós 7")], curiosities: [] },
  { id: "zacarias-israel", name: "Zacarias (Israel)", realm: "israel", order: 14, period: "Seis meses", verdict: "mau",
    summary: "Último rei da dinastia de Jeú.", history: "Foi assassinado por Salum, encerrando a quarta geração prometida a Jeú.",
    events: ["Conspiração de Salum."], godRelation: "Seguiu os pecados de Jeroboão.", people: ["Salum"], places: ["Samaria"],
    refs: [r("2rs", 15, "2 Reis 15")], curiosities: [] },
  { id: "salum-israel", name: "Salum", realm: "israel", order: 15, period: "Um mês", verdict: "mau",
    summary: "Reinou apenas um mês antes de ser morto por Menaém.", history: "Período de instabilidade e golpes sucessivos no Norte.",
    events: ["Golpe contra Zacarias.", "Morte às mãos de Menaém."], godRelation: "O texto o inclui entre os reis maus.",
    people: ["Zacarias", "Menaém"], places: ["Samaria"], refs: [r("2rs", 15, "2 Reis 15")], curiosities: [] },
  { id: "menaem", name: "Menaém", realm: "israel", order: 16, period: "Dez anos", verdict: "mau",
    summary: "Pagou pesado tributo ao rei da Assíria.", history: "Cobrou prata dos homens ricos de Israel para sustentar o trono.",
    events: ["Tributo a Pul (Tiglate-Pileser)."], godRelation: "Manteve os pecados de Jeroboão.", people: ["Pul, rei da Assíria"],
    places: ["Samaria", "Tirza"], refs: [r("2rs", 15, "2 Reis 15")], curiosities: [] },
  { id: "pecaias", name: "Pecaías", realm: "israel", order: 17, period: "Dois anos", verdict: "mau",
    summary: "Filho de Menaém, morto por seu capitão Peca.", history: "Reinou brevemente em Samaria.",
    events: ["Conspiração de Peca."], godRelation: "Seguiu os caminhos de seu pai.", people: ["Menaém", "Peca"],
    places: ["Samaria"], refs: [r("2rs", 15, "2 Reis 15")], curiosities: [] },
  { id: "peca", name: "Peca", realm: "israel", order: 18, period: "Vinte anos", verdict: "mau",
    summary: "Aliou-se à Síria contra Judá e perdeu territórios para a Assíria.", history: "Durante seu reinado começou a deportação de parte de Israel.",
    events: ["Guerra siro-efraimita contra Acaz.", "Primeiras deportações assírias."], godRelation: "O texto o avalia negativamente.",
    people: ["Rezim", "Acaz", "Tiglate-Pileser", "Oseias"], places: ["Samaria", "Gileade", "Galileia"],
    refs: [r("2rs", 15, "2 Reis 15"), r("2rs", 16, "2 Reis 16"), r("is", 7, "Isaías 7")], curiosities: [] },
  { id: "oseias-rei", name: "Oseias (rei)", realm: "israel", order: 19, period: "Nove anos", verdict: "mau",
    summary: "Último rei do Reino do Norte; Samaria caiu no seu tempo.", history: "Tentou apoio do Egito, deixou de pagar tributo à Assíria e foi preso; Samaria caiu depois de três anos de cerco.",
    events: ["Cerco e queda de Samaria.", "Deportação de Israel."], godRelation: "O texto explica a queda como consequência da persistente infidelidade do povo.",
    people: ["Salmaneser", "Só, rei do Egito"], places: ["Samaria", "Assíria"], refs: [r("2rs", 17, "2 Reis 17")],
    curiosities: ["Não confundir com o profeta Oseias, que tem o mesmo nome em português."] },

  /* ----------------------------- Reino de Judá ----------------------------- */
  { id: "roboao", name: "Roboão", realm: "juda", order: 1, period: "Dezessete anos", verdict: "mau",
    summary: "Filho de Salomão; em seu tempo o reino se dividiu.", history: "Rejeitou o conselho dos anciãos e respondeu com dureza ao povo, provocando a separação das dez tribos.",
    events: ["Assembleia de Siquém.", "Divisão do reino.", "Invasão de Sisaque, do Egito."],
    godRelation: "O texto registra momentos de humilhação diante do Senhor em meio à infidelidade.",
    people: ["Salomão", "Jeroboão I", "Semaías", "Sisaque"], places: ["Jerusalém", "Siquém"],
    refs: [r("1rs", 12, "1 Reis 12"), r("2cr", 12, "2 Crônicas 12")], curiosities: [] },
  { id: "abias", name: "Abias", realm: "juda", order: 2, period: "Três anos", verdict: "misto",
    summary: "Enfrentou Jeroboão em batalha e venceu.", history: "Crônicas registra seu discurso no monte Zemaraim antes da vitória.",
    events: ["Guerra contra Jeroboão."], godRelation: "Confiou no Senhor na batalha, mas o texto de Reis o avalia com reservas.",
    people: ["Roboão", "Jeroboão I"], places: ["Jerusalém", "Monte Zemaraim"], refs: [r("1rs", 15, "1 Reis 15"), r("2cr", 13, "2 Crônicas 13")], curiosities: [] },
  { id: "asa", name: "Asa", realm: "juda", order: 3, period: "Quarenta e um anos", verdict: "bom",
    summary: "Promoveu reforma religiosa e tirou os ídolos da terra.", history: "Buscou o Senhor por muitos anos, mas no fim confiou em aliança com a Síria e não buscou a Deus na doença.",
    events: ["Reforma e destruição de ídolos.", "Vitória sobre Zerá.", "Aliança com Ben-Hadade."],
    godRelation: "O coração de Asa foi reto durante a maior parte do reinado; foi repreendido pelo vidente Hanani no fim.",
    people: ["Hanani", "Baasa", "Ben-Hadade"], places: ["Jerusalém", "Mispa", "Gaba"], refs: [r("1rs", 15, "1 Reis 15"), r("2cr", 14, "2 Crônicas 14")], curiosities: [] },
  { id: "josafa", name: "Josafá", realm: "juda", order: 4, period: "Vinte e cinco anos", verdict: "bom",
    summary: "Enviou mestres para ensinar a Lei pelas cidades de Judá.", history: "Fortaleceu o reino e organizou a justiça, mas fez alianças problemáticas com a casa de Acabe.",
    events: ["Ensino da Lei pelo país.", "Aliança com Acabe.", "Vitória com louvor no vale de Beraca."],
    godRelation: "Buscou o Senhor e foi repreendido pelas alianças com reis ímpios.",
    people: ["Acabe", "Micaías", "Jeú, filho de Hanani"], places: ["Jerusalém", "En-Gedi", "Vale de Beraca"],
    refs: [r("1rs", 22, "1 Reis 22"), r("2cr", 17, "2 Crônicas 17"), r("2cr", 20, "2 Crônicas 20")], curiosities: [] },
  { id: "jorao-juda", name: "Jorão (Judá)", realm: "juda", order: 5, period: "Oito anos", verdict: "mau",
    summary: "Casou-se com uma filha da casa de Acabe e seguiu os caminhos de Israel.", history: "Matou os próprios irmãos e enfrentou revoltas de Edom e Libna.",
    events: ["Revolta de Edom.", "Carta de advertência de Elias."], godRelation: "O texto registra juízo severo sobre o seu reinado.",
    people: ["Atalia", "Elias", "Josafá"], places: ["Jerusalém", "Edom"], refs: [r("2rs", 8, "2 Reis 8"), r("2cr", 21, "2 Crônicas 21")], curiosities: [] },
  { id: "acazias-juda", name: "Acazias (Judá)", realm: "juda", order: 6, period: "Um ano", verdict: "mau",
    summary: "Reinou apenas um ano e morreu no levante de Jeú.", history: "Foi influenciado pela casa de Acabe, à qual estava ligado por parentesco.",
    events: ["Aliança com Jorão de Israel.", "Morte durante a revolta de Jeú."], godRelation: "Andou nos caminhos da casa de Acabe.",
    people: ["Atalia", "Jeú", "Jorão de Israel"], places: ["Jerusalém", "Jezreel"], refs: [r("2rs", 8, "2 Reis 8"), r("2rs", 9, "2 Reis 9")], curiosities: [] },
  { id: "atalia", name: "Atalia", realm: "juda", order: 7, period: "Seis anos", verdict: "mau",
    summary: "A única mulher a governar Judá; tomou o poder eliminando a descendência real.", history: "Foi deposta quando o sacerdote Joiada apresentou Joás, escondido no templo desde criança.",
    events: ["Matança da descendência real.", "Joás escondido por Jeoseba.", "Coroação de Joás e queda de Atalia."],
    godRelation: "Promoveu o culto a Baal em Jerusalém.", people: ["Joiada", "Jeoseba", "Joás"], places: ["Jerusalém", "Templo"],
    refs: [r("2rs", 11, "2 Reis 11"), r("2cr", 22, "2 Crônicas 22")], curiosities: ["O texto não a chama de rainha legítima da linhagem davídica."] },
  { id: "joas-juda", name: "Joás (Judá)", realm: "juda", order: 8, period: "Quarenta anos", verdict: "misto",
    summary: "Tornou-se rei aos sete anos e restaurou o Templo.", history: "Foi fiel enquanto viveu o sacerdote Joiada; depois se desviou e mandou matar o filho dele, Zacarias.",
    events: ["Coroação ainda menino.", "Reparo do Templo.", "Desvio após a morte de Joiada."],
    godRelation: "Fez o que era reto sob a orientação de Joiada, e se afastou depois.",
    people: ["Joiada", "Jeoseba", "Zacarias, filho de Joiada"], places: ["Jerusalém", "Templo"],
    refs: [r("2rs", 12, "2 Reis 12"), r("2cr", 24, "2 Crônicas 24")], curiosities: [] },
  { id: "amazias", name: "Amazias", realm: "juda", order: 9, period: "Vinte e nove anos", verdict: "misto",
    summary: "Venceu Edom e depois se envolveu em guerra desastrosa com Israel.", history: "Trouxe ídolos de Edom e foi advertido por um profeta.",
    events: ["Vitória no vale do Sal.", "Derrota diante de Jeoás de Israel.", "Saque de Jerusalém."],
    godRelation: "Fez o que era reto, mas não de coração perfeito, segundo o texto.",
    people: ["Jeoás de Israel"], places: ["Jerusalém", "Vale do Sal", "Bete-Semes"], refs: [r("2rs", 14, "2 Reis 14"), r("2cr", 25, "2 Crônicas 25")], curiosities: [] },
  { id: "uzias", name: "Uzias (Azarias)", realm: "juda", order: 10, period: "Cinquenta e dois anos", verdict: "misto",
    summary: "Reinado longo e forte, encerrado com lepra após entrar no Templo para queimar incenso.", history: "Fortificou Jerusalém, organizou o exército e prosperou enquanto buscou o Senhor.",
    events: ["Vitórias militares e obras de fortificação.", "Entrada indevida no Templo e lepra."],
    godRelation: "Buscou a Deus nos dias de Zacarias, o vidente; o orgulho marcou o seu fim.",
    people: ["Zacarias, o vidente", "Isaías", "Jotão"], places: ["Jerusalém"],
    refs: [r("2rs", 15, "2 Reis 15"), r("2cr", 26, "2 Crônicas 26"), r("is", 6, "Isaías 6")],
    curiosities: ["Isaías teve sua visão no templo no ano da morte do rei Uzias."] },
  { id: "jotao", name: "Jotão", realm: "juda", order: 11, period: "Dezesseis anos", verdict: "bom",
    summary: "Fortaleceu-se porque dirigiu os seus caminhos perante o Senhor.", history: "Construiu a porta alta do Templo e venceu os amonitas.",
    events: ["Obras no Templo e nas muralhas.", "Vitória sobre Amom."], godRelation: "O texto o avalia positivamente, notando que o povo ainda agia corruptamente.",
    people: ["Uzias", "Acaz"], places: ["Jerusalém"], refs: [r("2rs", 15, "2 Reis 15"), r("2cr", 27, "2 Crônicas 27")], curiosities: [] },
  { id: "acaz", name: "Acaz", realm: "juda", order: 12, period: "Dezesseis anos", verdict: "mau",
    summary: "Buscou socorro na Assíria em vez de confiar no Senhor.", history: "Enfrentou a coligação de Israel e Síria e recebeu de Isaías o sinal do Emanuel.",
    events: ["Guerra siro-efraimita.", "Sinal do Emanuel anunciado por Isaías.", "Altar copiado de Damasco."],
    godRelation: "Recusou pedir um sinal ao Senhor e promoveu cultos estrangeiros.",
    people: ["Isaías", "Peca", "Rezim", "Tiglate-Pileser"], places: ["Jerusalém", "Damasco"],
    refs: [r("2rs", 16, "2 Reis 16"), r("is", 7, "Isaías 7")], curiosities: [] },
  { id: "ezequias", name: "Ezequias", realm: "juda", order: 13, period: "Vinte e nove anos", verdict: "bom",
    summary: "Grande reformador; confiou no Senhor durante o cerco assírio.", history: "Purificou o Templo, restaurou a Páscoa e viu Jerusalém livrada do exército de Senaqueribe.",
    events: ["Reforma religiosa e restauração da Páscoa.", "Cerco de Senaqueribe e livramento.", "Doença e quinze anos acrescentados.", "Visita dos enviados da Babilônia."],
    godRelation: "O texto diz que confiou no Senhor como nenhum outro rei de Judá.",
    people: ["Isaías", "Senaqueribe", "Manassés"], places: ["Jerusalém", "Laquis"],
    refs: [r("2rs", 18, "2 Reis 18"), r("2rs", 19, "2 Reis 19"), r("2cr", 30, "2 Crônicas 30"), r("is", 37, "Isaías 37")],
    curiosities: ["Mandou abrir um túnel para levar água à cidade em tempo de cerco."] },
  { id: "manasses", name: "Manassés", realm: "juda", order: 14, period: "Cinquenta e cinco anos", verdict: "misto",
    summary: "O reinado mais longo de Judá; extremamente idólatra, arrependeu-se no cativeiro.", history: "Reintroduziu cultos pagãos, foi levado preso à Babilônia e, humilhado, buscou o Senhor.",
    events: ["Idolatria intensa em Jerusalém.", "Prisão e humilhação.", "Arrependimento e reformas tardias."],
    godRelation: "Crônicas registra que orou, foi ouvido e restituído ao seu reino.",
    people: ["Ezequias", "Amom"], places: ["Jerusalém", "Babilônia"], refs: [r("2rs", 21, "2 Reis 21"), r("2cr", 33, "2 Crônicas 33")], curiosities: [] },
  { id: "amom", name: "Amom", realm: "juda", order: 15, period: "Dois anos", verdict: "mau",
    summary: "Seguiu a idolatria do pai e foi morto por seus servos.", history: "Seu reinado curto terminou em conspiração palaciana.",
    events: ["Idolatria.", "Conspiração dos servos."], godRelation: "O texto diz que não se humilhou como seu pai Manassés.",
    people: ["Manassés", "Josias"], places: ["Jerusalém"], refs: [r("2rs", 21, "2 Reis 21"), r("2cr", 33, "2 Crônicas 33")], curiosities: [] },
  { id: "josias", name: "Josias", realm: "juda", order: 16, period: "Trinta e um anos", verdict: "bom",
    summary: "Encontrou o Livro da Lei e conduziu a maior reforma religiosa de Judá.", history: "Começou a reinar com oito anos, purificou a terra dos ídolos e celebrou uma Páscoa marcante.",
    events: ["Descoberta do Livro da Lei no Templo.", "Reforma nacional.", "Páscoa em Jerusalém.", "Morte em Megido."],
    godRelation: "O texto diz que não houve antes dele rei que se voltasse ao Senhor com tanto empenho.",
    people: ["Hilquias", "Hulda", "Jeremias", "Faraó Neco"], places: ["Jerusalém", "Betel", "Megido"],
    refs: [r("2rs", 22, "2 Reis 22"), r("2rs", 23, "2 Reis 23"), r("2cr", 34, "2 Crônicas 34")], curiosities: [] },
  { id: "jeoacaz-juda", name: "Jeoacaz (Judá)", realm: "juda", order: 17, period: "Três meses", verdict: "mau",
    summary: "Deposto pelo faraó Neco e levado para o Egito.", history: "Reinou brevemente após a morte de Josias.",
    events: ["Deposição por Neco.", "Deportação para o Egito."], godRelation: "O texto o avalia negativamente.",
    people: ["Josias", "Faraó Neco"], places: ["Jerusalém", "Ribla", "Egito"], refs: [r("2rs", 23, "2 Reis 23")], curiosities: [] },
  { id: "jeoaquim", name: "Jeoaquim", realm: "juda", order: 18, period: "Onze anos", verdict: "mau",
    summary: "Queimou o rolo com as palavras de Jeremias.", history: "Vassalo do Egito e depois da Babilônia, rebelou-se e viu o início das deportações.",
    events: ["Tributo ao Egito.", "Submissão a Nabucodonosor.", "Queima do rolo de Jeremias."],
    godRelation: "Rejeitou abertamente a palavra profética.", people: ["Jeremias", "Baruque", "Nabucodonosor"],
    places: ["Jerusalém"], refs: [r("2rs", 24, "2 Reis 24"), r("jr", 36, "Jeremias 36")], curiosities: [] },
  { id: "joaquim", name: "Joaquim (Jeconias)", realm: "juda", order: 19, period: "Três meses", verdict: "mau",
    summary: "Levado cativo à Babilônia na deportação de sua época.", history: "Anos depois foi libertado da prisão e comeu à mesa do rei da Babilônia.",
    events: ["Rendição de Jerusalém.", "Deportação com a elite do reino.", "Libertação no reinado de Evil-Merodaque."],
    godRelation: "O texto o avalia negativamente, mas registra misericórdia no fim da vida.",
    people: ["Nabucodonosor", "Ezequiel", "Evil-Merodaque"], places: ["Jerusalém", "Babilônia"],
    refs: [r("2rs", 24, "2 Reis 24"), r("2rs", 25, "2 Reis 25")], curiosities: ["Aparece na genealogia de Jesus em Mateus 1."] },
  { id: "zedequias", name: "Zedequias", realm: "juda", order: 20, period: "Onze anos", verdict: "mau",
    summary: "Último rei de Judá; no seu reinado Jerusalém e o Templo foram destruídos.", history: "Rebelou-se contra a Babilônia apesar das advertências de Jeremias.",
    events: ["Cerco de Jerusalém.", "Queda da cidade e destruição do Templo.", "Exílio do povo."],
    godRelation: "Não se humilhou diante da palavra do Senhor por meio de Jeremias.",
    people: ["Jeremias", "Nabucodonosor"], places: ["Jerusalém", "Ribla", "Babilônia"],
    refs: [r("2rs", 25, "2 Reis 25"), r("jr", 39, "Jeremias 39"), r("2cr", 36, "2 Crônicas 36")], curiosities: [] },
];

export function kingById(id: string): BibleKing | undefined {
  return BIBLE_KINGS.find((k) => k.id === id);
}

export function kingsByRealm(realm: Realm): BibleKing[] {
  return BIBLE_KINGS.filter((k) => k.realm === realm).sort((a, b) => a.order - b.order);
}