import type { BibleRef } from "@/lib/atlas-shared";

export type BiblePlace = {
  id: string;
  name: string;
  emoji: string;
  region: string;
  /** localização atual conhecida — string vazia quando incerta */
  modern: string;
  coords: { lat: number; lng: number };
  summary: string;
  events: string[];
  people: string[];
  verses: { ref: string; text: string; book: string; chapter: number }[];
  history: string;
  curiosities: string[];
  refs: BibleRef[];
  /**
   * Descoberta: o local é revelado quando o usuário lê QUALQUER um destes
   * capítulos (mesma base de dados da Jornada Bíblica).
   * `core: true` = sempre disponível, sem bloqueio.
   */
  core?: boolean;
  discoverBy?: { book: string; chapter: number }[];
};

const r = (book: string, chapter: number, label: string): BibleRef => ({ book, chapter, label });

export const BIBLE_PLACES: BiblePlace[] = [
  {
    id: "jerusalem",
    name: "Jerusalém",
    emoji: "🏛️",
    region: "Judá",
    modern: "Jerusalém, Israel",
    coords: { lat: 31.78, lng: 35.22 },
    core: true,
    summary: "A cidade escolhida para o Templo, centro da adoração de Israel e cenário da morte e ressurreição de Jesus.",
    events: [
      "Davi conquista a fortaleza de Sião e faz dela a capital do reino.",
      "Salomão constrói o Templo.",
      "Destruição do Templo pelos babilônios e posterior reconstrução.",
      "Entrada triunfal, crucificação e ressurreição de Jesus.",
      "Descida do Espírito Santo no Pentecostes.",
    ],
    people: ["Melquisedeque", "Davi", "Salomão", "Ezequias", "Josias", "Neemias", "Jesus", "Pedro", "Tiago"],
    verses: [
      { ref: "Salmos 122:6", text: "Orai pela paz de Jerusalém; prosperarão aqueles que te amam.", book: "sl", chapter: 122 },
      { ref: "Atos 1:8", text: "Sereis minhas testemunhas, tanto em Jerusalém como em toda a Judeia.", book: "atos", chapter: 1 },
    ],
    history:
      "Cidade fortificada sobre colinas, cercada por vales profundos. Foi capital do Reino Unido, depois do Reino de Judá, caiu diante da Babilônia em 586 a.C. e foi reconstruída após o exílio. No período do Novo Testamento estava sob domínio romano.",
    curiosities: [
      "Aparece na Bíblia com vários nomes: Salém, Sião, Cidade de Davi.",
      "O Templo foi construído no monte Moriá, ligado à história de Abraão e Isaque.",
    ],
    refs: [r("2sm", 5, "2 Samuel 5"), r("1rs", 8, "1 Reis 8"), r("lc", 19, "Lucas 19"), r("atos", 2, "Atos 2")],
  },
  {
    id: "belem",
    name: "Belém",
    emoji: "⭐",
    region: "Judá",
    modern: "Belém, Cisjordânia",
    coords: { lat: 31.7, lng: 35.2 },
    core: true,
    summary: "A pequena cidade de Judá onde nasceram Davi e, séculos depois, Jesus.",
    events: [
      "História de Rute e Boaz nos campos de Belém.",
      "Unção de Davi por Samuel.",
      "Nascimento de Jesus e visita dos pastores.",
    ],
    people: ["Rute", "Boaz", "Jessé", "Davi", "Samuel", "Maria", "José", "Jesus"],
    verses: [
      { ref: "Miqueias 5:2", text: "E tu, Belém Efrata, posto que pequena entre os milhares de Judá, de ti me sairá o que governará em Israel.", book: "mq", chapter: 5 },
      { ref: "Lucas 2:11", text: "Na cidade de Davi vos nasceu hoje o Salvador, que é Cristo, o Senhor.", book: "lc", chapter: 2 },
    ],
    history:
      "Chamada também de Belém Efrata para distingui-la de outra Belém em Zebulom. Ficava numa região agrícola, cerca de 9 km ao sul de Jerusalém.",
    curiosities: ["O nome significa 'casa do pão'.", "Era a cidade da família de Jessé, pai de Davi."],
    refs: [r("rt", 1, "Rute 1"), r("1sm", 16, "1 Samuel 16"), r("lc", 2, "Lucas 2"), r("mt", 2, "Mateus 2")],
  },
  {
    id: "nazare",
    name: "Nazaré",
    emoji: "🏡",
    region: "Galileia",
    modern: "Nazaré, Israel",
    coords: { lat: 32.7, lng: 35.3 },
    core: true,
    summary: "Vilarejo da Galileia onde Jesus cresceu e viveu a maior parte da sua vida.",
    events: [
      "Anúncio do anjo Gabriel a Maria.",
      "Infância e juventude de Jesus.",
      "Jesus lê Isaías na sinagoga e é rejeitado pelos conterrâneos.",
    ],
    people: ["Maria", "José", "Jesus"],
    verses: [
      { ref: "Lucas 4:18", text: "O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres.", book: "lc", chapter: 4 },
      { ref: "João 1:46", text: "Pode vir alguma coisa boa de Nazaré?", book: "jo", chapter: 1 },
    ],
    history: "Aldeia pequena e sem destaque político, situada nas colinas da baixa Galileia, longe das principais rotas de comércio.",
    curiosities: ["Nazaré não é citada no Antigo Testamento.", "Jesus ficou conhecido como 'o nazareno'."],
    refs: [r("lc", 1, "Lucas 1"), r("lc", 4, "Lucas 4"), r("mt", 13, "Mateus 13")],
  },
  {
    id: "jerico",
    name: "Jericó",
    emoji: "🧱",
    region: "Vale do Jordão",
    modern: "Jericó, Cisjordânia",
    coords: { lat: 31.87, lng: 35.44 },
    summary: "A primeira cidade conquistada por Israel em Canaã, famosa pela queda de seus muros.",
    events: [
      "Os espias são escondidos por Raabe.",
      "Queda dos muros após sete dias de marcha ao redor da cidade.",
      "Elias e Eliseu passam por Jericó antes do arrebatamento de Elias.",
      "Jesus cura Bartimeu e se hospeda na casa de Zaqueu.",
    ],
    people: ["Josué", "Raabe", "Eliseu", "Bartimeu", "Zaqueu", "Jesus"],
    verses: [
      { ref: "Josué 6:20", text: "O povo jubilou, e tocaram-se as buzinas... e o muro caiu abaixo.", book: "js", chapter: 6 },
      { ref: "Lucas 19:9", text: "Hoje veio a salvação a esta casa.", book: "lc", chapter: 19 },
    ],
    history: "Cidade de oásis no vale do Jordão, uma das mais antigas povoações conhecidas, guardando o acesso às montanhas centrais de Canaã.",
    curiosities: ["É chamada de 'cidade das palmeiras'.", "Fica bem abaixo do nível do mar."],
    refs: [r("js", 2, "Josué 2"), r("js", 6, "Josué 6"), r("lc", 19, "Lucas 19")],
    discoverBy: [{ book: "js", chapter: 6 }, { book: "js", chapter: 2 }, { book: "lc", chapter: 19 }],
  },
  {
    id: "egito",
    name: "Egito",
    emoji: "🐫",
    region: "Norte da África",
    modern: "Egito",
    coords: { lat: 30.05, lng: 31.24 },
    core: true,
    summary: "Terra de refúgio e de escravidão: cenário da história de José, do Êxodo e da fuga da família de Jesus.",
    events: [
      "José é vendido e se torna governador do Egito.",
      "Israel se multiplica e depois é escravizado.",
      "As dez pragas e a saída do povo com Moisés.",
      "José, Maria e o menino Jesus fogem para o Egito.",
    ],
    people: ["Abraão", "José", "Faraó", "Moisés", "Arão", "Jesus"],
    verses: [
      { ref: "Êxodo 3:10", text: "Vem agora, e enviar-te-ei a Faraó, para que tires o meu povo do Egito.", book: "ex", chapter: 3 },
      { ref: "Oseias 11:1", text: "Do Egito chamei o meu filho.", book: "os", chapter: 11 },
    ],
    history: "Grande potência do mundo antigo, organizada ao longo do rio Nilo. Israel viveu na região de Gósen, no delta, antes do Êxodo.",
    curiosities: ["O Egito aparece tanto como abrigo em tempos de fome quanto como símbolo de opressão."],
    refs: [r("gn", 41, "Gênesis 41"), r("ex", 12, "Êxodo 12"), r("mt", 2, "Mateus 2")],
  },
  {
    id: "sinai",
    name: "Monte Sinai",
    emoji: "⛰️",
    region: "Península do Sinai",
    modern: "Tradicionalmente identificado com o Jebel Musa, no Egito (identificação incerta)",
    coords: { lat: 28.54, lng: 33.97 },
    summary: "O monte onde Deus entregou a Lei a Moisés e firmou a aliança com Israel.",
    events: [
      "A sarça ardente e o chamado de Moisés (monte Horebe).",
      "Entrega dos Dez Mandamentos.",
      "O bezerro de ouro e a renovação das tábuas.",
      "Elias encontra Deus na brisa suave.",
    ],
    people: ["Moisés", "Arão", "Josué", "Elias"],
    verses: [
      { ref: "Êxodo 19:20", text: "E desceu o Senhor sobre o monte Sinai, sobre o cume do monte.", book: "ex", chapter: 19 },
      { ref: "Êxodo 20:2", text: "Eu sou o Senhor teu Deus, que te tirei da terra do Egito.", book: "ex", chapter: 20 },
    ],
    history: "Também chamado de Horebe. Sua localização exata é debatida; a tradição mais antiga aponta para o sul da península do Sinai.",
    curiosities: ["A Bíblia usa os nomes Sinai e Horebe para o mesmo lugar."],
    refs: [r("ex", 19, "Êxodo 19"), r("ex", 20, "Êxodo 20"), r("1rs", 19, "1 Reis 19")],
    discoverBy: [{ book: "ex", chapter: 19 }, { book: "ex", chapter: 20 }, { book: "ex", chapter: 3 }],
  },
  {
    id: "mar-vermelho",
    name: "Mar Vermelho",
    emoji: "🌊",
    region: "Entre o Egito e o Sinai",
    modern: "Mar Vermelho / região dos lagos do istmo de Suez (ponto exato desconhecido)",
    coords: { lat: 29.5, lng: 32.6 },
    summary: "A passagem impossível que se abriu diante do povo de Israel na saída do Egito.",
    events: ["Israel atravessa em seco.", "O exército egípcio é vencido pelas águas.", "O cântico de Moisés e de Miriã."],
    people: ["Moisés", "Arão", "Miriã", "Faraó"],
    verses: [
      { ref: "Êxodo 14:14", text: "O Senhor pelejará por vós, e vos calareis.", book: "ex", chapter: 14 },
      { ref: "Êxodo 15:2", text: "O Senhor é a minha força e o meu cântico.", book: "ex", chapter: 15 },
    ],
    history: "O texto hebraico fala do 'Mar de Juncos'. O local exato da travessia é discutido por estudiosos.",
    curiosities: ["A travessia é lembrada em vários salmos como marco da libertação."],
    refs: [r("ex", 14, "Êxodo 14"), r("ex", 15, "Êxodo 15")],
    discoverBy: [{ book: "ex", chapter: 14 }],
  },
  {
    id: "jordao",
    name: "Rio Jordão",
    emoji: "💧",
    region: "Vale do Jordão",
    modern: "Rio Jordão, entre Israel e a Jordânia",
    coords: { lat: 32.31, lng: 35.57 },
    core: true,
    summary: "O rio da travessia para a Terra Prometida e do batismo de Jesus.",
    events: [
      "Israel atravessa em seco com a arca da aliança.",
      "Elias é arrebatado depois de dividir as águas com Eliseu.",
      "Naamã é curado ao mergulhar sete vezes.",
      "João Batista batiza Jesus.",
    ],
    people: ["Josué", "Elias", "Eliseu", "Naamã", "João Batista", "Jesus"],
    verses: [
      { ref: "Josué 3:17", text: "Todo o Israel passou em seco, até que todo o povo acabou de passar o Jordão.", book: "js", chapter: 3 },
      { ref: "Mateus 3:16", text: "Jesus, depois de ser batizado, saiu logo da água.", book: "mt", chapter: 3 },
    ],
    history: "Nasce ao norte, atravessa o mar da Galileia e desce até o mar Morto, formando o vale mais baixo da terra.",
    curiosities: ["Foi fronteira natural entre o deserto e a terra habitada."],
    refs: [r("js", 3, "Josué 3"), r("2rs", 5, "2 Reis 5"), r("mt", 3, "Mateus 3")],
  },
  {
    id: "galileia",
    name: "Mar da Galileia",
    emoji: "⛵",
    region: "Galileia",
    modern: "Lago de Tiberíades, Israel",
    coords: { lat: 32.82, lng: 35.59 },
    core: true,
    summary: "O lago onde Jesus chamou seus primeiros discípulos e realizou vários milagres.",
    events: [
      "Chamado de Pedro, André, Tiago e João.",
      "Jesus acalma a tempestade.",
      "Jesus anda sobre as águas.",
      "A pesca maravilhosa e o café da manhã com o Ressuscitado.",
    ],
    people: ["Jesus", "Pedro", "André", "Tiago", "João"],
    verses: [
      { ref: "Marcos 4:39", text: "Cala-te, aquieta-te. E o vento se aquietou, e houve grande bonança.", book: "mc", chapter: 4 },
      { ref: "João 21:6", text: "Lançai a rede para o lado direito do barco, e achareis.", book: "jo", chapter: 21 },
    ],
    history: "Lago de água doce cercado por colinas, conhecido por tempestades repentinas. Sustentava uma ativa indústria de pesca.",
    curiosities: ["Também é chamado de mar de Quinerete, lago de Genesaré e mar de Tiberíades."],
    refs: [r("mc", 4, "Marcos 4"), r("mt", 14, "Mateus 14"), r("jo", 21, "João 21")],
  },
  {
    id: "cafarnaum",
    name: "Cafarnaum",
    emoji: "🏘️",
    region: "Galileia",
    modern: "Sítio arqueológico de Cafarnaum, Israel",
    coords: { lat: 32.88, lng: 35.57 },
    summary: "A cidade que Jesus tomou como base do seu ministério na Galileia.",
    events: [
      "Cura da sogra de Pedro.",
      "Cura do paralítico descido pelo telhado.",
      "Ensino sobre o pão da vida na sinagoga.",
    ],
    people: ["Jesus", "Pedro", "Mateus", "o centurião"],
    verses: [
      { ref: "Mateus 4:13", text: "Deixando Nazaré, foi habitar em Cafarnaum, cidade marítima.", book: "mt", chapter: 4 },
      { ref: "João 6:35", text: "Eu sou o pão da vida.", book: "jo", chapter: 6 },
    ],
    history: "Vila de pescadores à beira do lago, com posto de cobrança de impostos e uma sinagoga.",
    curiosities: ["É chamada de 'sua cidade' nos Evangelhos, referindo-se a Jesus."],
    refs: [r("mt", 4, "Mateus 4"), r("mc", 2, "Marcos 2"), r("jo", 6, "João 6")],
    discoverBy: [{ book: "mt", chapter: 4 }, { book: "mc", chapter: 2 }, { book: "jo", chapter: 6 }],
  },
  {
    id: "samaria",
    name: "Samaria",
    emoji: "🏔️",
    region: "Reino do Norte",
    modern: "Sebastia, Cisjordânia",
    coords: { lat: 32.28, lng: 35.19 },
    summary: "Capital do Reino de Israel e, no Novo Testamento, região de encontro entre judeus e samaritanos.",
    events: [
      "Onri compra o monte e edifica a cidade.",
      "Confronto entre Elias e os profetas de Baal no reinado de Acabe.",
      "Queda diante da Assíria.",
      "Filipe prega o Evangelho na Samaria.",
    ],
    people: ["Onri", "Acabe", "Jezabel", "Elias", "Eliseu", "Filipe"],
    verses: [
      { ref: "João 4:14", text: "Aquele que beber da água que eu lhe der nunca terá sede.", book: "jo", chapter: 4 },
      { ref: "Atos 8:5", text: "E, descendo Filipe à cidade de Samaria, lhes pregava a Cristo.", book: "atos", chapter: 8 },
    ],
    history: "Fundada por Onri por volta do século IX a.C., foi capital do Reino do Norte até a conquista assíria em 722 a.C.",
    curiosities: ["O nome passou a designar tanto a cidade quanto toda a região central."],
    refs: [r("1rs", 16, "1 Reis 16"), r("2rs", 17, "2 Reis 17"), r("jo", 4, "João 4"), r("atos", 8, "Atos 8")],
    discoverBy: [{ book: "jo", chapter: 4 }, { book: "2rs", chapter: 17 }],
  },
  {
    id: "hebrom",
    name: "Hebrom",
    emoji: "🌳",
    region: "Judá",
    modern: "Hebrom, Cisjordânia",
    coords: { lat: 31.53, lng: 35.1 },
    summary: "Cidade dos patriarcas e primeira capital do reinado de Davi.",
    events: [
      "Abraão habita junto aos carvalhos de Manre.",
      "Sepultamento de Sara e dos patriarcas na cova de Macpela.",
      "Davi é ungido rei sobre Judá e reina ali sete anos.",
    ],
    people: ["Abraão", "Sara", "Isaque", "Jacó", "Calebe", "Davi", "Absalão"],
    verses: [
      { ref: "Gênesis 13:18", text: "E Abrão... veio, e habitou nos carvalhais de Manre, que estão junto a Hebrom.", book: "gn", chapter: 13 },
      { ref: "2 Samuel 5:5", text: "Em Hebrom reinou sobre Judá sete anos e seis meses.", book: "2sm", chapter: 5 },
    ],
    history: "Cidade antiga nas montanhas de Judá, designada cidade de refúgio e território de Calebe.",
    curiosities: ["Foi capital de Davi antes de Jerusalém."],
    refs: [r("gn", 23, "Gênesis 23"), r("2sm", 2, "2 Samuel 2"), r("2sm", 5, "2 Samuel 5")],
    discoverBy: [{ book: "gn", chapter: 23 }, { book: "2sm", chapter: 2 }],
  },
  {
    id: "betania",
    name: "Betânia",
    emoji: "🕯️",
    region: "Judeia",
    modern: "Al-Eizariya, Cisjordânia",
    coords: { lat: 31.77, lng: 35.26 },
    summary: "Vila próxima a Jerusalém, casa de Lázaro, Marta e Maria.",
    events: [
      "Ressurreição de Lázaro.",
      "Maria unge os pés de Jesus.",
      "Jesus abençoa os discípulos antes de ser elevado ao céu.",
    ],
    people: ["Lázaro", "Marta", "Maria", "Simão, o leproso", "Jesus"],
    verses: [
      { ref: "João 11:25", text: "Eu sou a ressurreição e a vida.", book: "jo", chapter: 11 },
      { ref: "Lucas 24:50", text: "E levou-os fora, até Betânia; e, levantando as mãos, os abençoou.", book: "lc", chapter: 24 },
    ],
    history: "Ficava a poucos quilômetros de Jerusalém, na encosta oriental do monte das Oliveiras.",
    curiosities: ["Jesus se hospedava ali durante a última semana antes da cruz."],
    refs: [r("jo", 11, "João 11"), r("mc", 14, "Marcos 14"), r("lc", 24, "Lucas 24")],
    discoverBy: [{ book: "jo", chapter: 11 }, { book: "lc", chapter: 24 }],
  },
  {
    id: "damasco",
    name: "Damasco",
    emoji: "✨",
    region: "Síria",
    modern: "Damasco, Síria",
    coords: { lat: 33.51, lng: 36.29 },
    summary: "Cidade da conversão de Saulo de Tarso, no caminho que mudou a história da Igreja.",
    events: [
      "Encontro de Saulo com o Cristo ressuscitado.",
      "Ananias ora por Saulo e ele recupera a visão.",
      "Paulo escapa da cidade descido num cesto pelo muro.",
    ],
    people: ["Saulo de Tarso (Paulo)", "Ananias", "Naamã", "Eliseu"],
    verses: [
      { ref: "Atos 9:4", text: "Saulo, Saulo, por que me persegues?", book: "atos", chapter: 9 },
      { ref: "Atos 9:20", text: "E logo nas sinagogas pregava a Jesus, que este era o Filho de Deus.", book: "atos", chapter: 9 },
    ],
    history: "Uma das cidades continuamente habitadas mais antigas do mundo, capital da Síria antiga e ponto de rotas comerciais.",
    curiosities: ["A 'rua Direita', citada em Atos, ainda é conhecida em Damasco."],
    refs: [r("atos", 9, "Atos 9"), r("2rs", 5, "2 Reis 5")],
    discoverBy: [{ book: "atos", chapter: 9 }],
  },
  {
    id: "efeso",
    name: "Éfeso",
    emoji: "🏛️",
    region: "Ásia Menor",
    modern: "Sítio arqueológico de Éfeso, Turquia",
    coords: { lat: 37.94, lng: 27.34 },
    summary: "Grande cidade da Ásia onde Paulo ensinou por cerca de três anos.",
    events: [
      "Ministério de Paulo na escola de Tirano.",
      "Tumulto dos ourives ligados ao templo de Diana.",
      "Despedida de Paulo dos presbíteros de Éfeso, em Mileto.",
      "Carta à igreja de Éfeso no Apocalipse.",
    ],
    people: ["Paulo", "Áquila", "Priscila", "Apolo", "Timóteo", "João"],
    verses: [
      { ref: "Efésios 2:8", text: "Porque pela graça sois salvos, por meio da fé.", book: "ef", chapter: 2 },
      { ref: "Apocalipse 2:4", text: "Tenho contra ti que deixaste o teu primeiro amor.", book: "ap", chapter: 2 },
    ],
    history: "Porto movimentado e centro religioso da Ásia romana, famoso pelo templo de Ártemis (Diana).",
    curiosities: ["Timóteo pastoreou a igreja dessa cidade."],
    refs: [r("atos", 19, "Atos 19"), r("ef", 1, "Efésios 1"), r("ap", 2, "Apocalipse 2")],
    discoverBy: [{ book: "atos", chapter: 19 }, { book: "ef", chapter: 1 }],
  },
  {
    id: "corinto",
    name: "Corinto",
    emoji: "⚓",
    region: "Acaia (Grécia)",
    modern: "Corinto, Grécia",
    coords: { lat: 37.9, lng: 22.88 },
    summary: "Cidade portuária grega que recebeu duas das cartas mais práticas de Paulo.",
    events: [
      "Paulo trabalha com Áquila e Priscila fazendo tendas.",
      "Fundação da igreja e permanência de cerca de um ano e meio.",
      "Cartas tratando de divisões, dons espirituais e amor.",
    ],
    people: ["Paulo", "Áquila", "Priscila", "Silas", "Timóteo", "Apolo"],
    verses: [
      { ref: "1 Coríntios 13:13", text: "Agora, pois, permanecem a fé, a esperança e o amor; mas o maior destes é o amor.", book: "1co", chapter: 13 },
      { ref: "2 Coríntios 12:9", text: "A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", book: "2co", chapter: 12 },
    ],
    history: "Situada no istmo entre dois portos, era rica, cosmopolita e conhecida pela vida moral relaxada.",
    curiosities: ["O capítulo do amor (1 Coríntios 13) foi escrito para essa igreja dividida."],
    refs: [r("atos", 18, "Atos 18"), r("1co", 13, "1 Coríntios 13")],
    discoverBy: [{ book: "atos", chapter: 18 }, { book: "1co", chapter: 13 }],
  },
  {
    id: "roma",
    name: "Roma",
    emoji: "🦅",
    region: "Itália",
    modern: "Roma, Itália",
    coords: { lat: 41.9, lng: 12.5 },
    summary: "Capital do Império e destino final da viagem missionária de Paulo em Atos.",
    events: [
      "Paulo chega preso e prega em prisão domiciliar.",
      "Carta aos Romanos, escrita antes da chegada.",
      "A igreja cresce na capital do Império.",
    ],
    people: ["Paulo", "Áquila", "Priscila", "Febe", "César"],
    verses: [
      { ref: "Romanos 1:16", text: "Não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação.", book: "rm", chapter: 1 },
      { ref: "Atos 28:31", text: "Pregando o reino de Deus... com toda a liberdade, sem impedimento algum.", book: "atos", chapter: 28 },
    ],
    history: "Centro político do mundo mediterrâneo no primeiro século, com estradas que facilitaram a expansão do Evangelho.",
    curiosities: ["O livro de Atos termina com Paulo pregando em Roma."],
    refs: [r("rm", 1, "Romanos 1"), r("atos", 28, "Atos 28")],
    discoverBy: [{ book: "atos", chapter: 28 }, { book: "rm", chapter: 1 }],
  },
  {
    id: "antioquia",
    name: "Antioquia",
    emoji: "🕊️",
    region: "Síria",
    modern: "Antáquia, Turquia",
    coords: { lat: 36.2, lng: 36.16 },
    summary: "Base das viagens missionárias e cidade onde os discípulos foram chamados cristãos pela primeira vez.",
    events: [
      "Igreja formada por judeus e gentios.",
      "Barnabé busca Saulo para ensinar ali.",
      "Envio de Paulo e Barnabé para a primeira viagem missionária.",
    ],
    people: ["Barnabé", "Paulo", "Pedro", "Ágabo", "Simeão"],
    verses: [
      { ref: "Atos 11:26", text: "E em Antioquia foram os discípulos, pela primeira vez, chamados cristãos.", book: "atos", chapter: 11 },
      { ref: "Atos 13:2", text: "Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.", book: "atos", chapter: 13 },
    ],
    history: "Terceira maior cidade do Império Romano, ponto de encontro de culturas na Síria.",
    curiosities: ["Existe também Antioquia da Pisídia, uma cidade diferente, visitada por Paulo."],
    refs: [r("atos", 11, "Atos 11"), r("atos", 13, "Atos 13")],
    discoverBy: [{ book: "atos", chapter: 11 }, { book: "atos", chapter: 13 }],
  },
  {
    id: "cesareia",
    name: "Cesareia",
    emoji: "🌅",
    region: "Costa da Judeia",
    modern: "Parque Nacional de Cesareia Marítima, Israel",
    coords: { lat: 32.5, lng: 34.89 },
    summary: "Porto romano onde o Evangelho alcançou oficialmente os gentios.",
    events: [
      "Pedro prega na casa de Cornélio.",
      "Filipe, o evangelista, habita ali.",
      "Paulo fica preso cerca de dois anos e apela a César.",
    ],
    people: ["Cornélio", "Pedro", "Filipe", "Paulo", "Félix", "Festo", "Agripa"],
    verses: [
      { ref: "Atos 10:34", text: "Reconheço por verdade que Deus não faz acepção de pessoas.", book: "atos", chapter: 10 },
      { ref: "Atos 25:11", text: "Para César apelo.", book: "atos", chapter: 25 },
    ],
    history: "Construída por Herodes, o Grande, era sede do governo romano na província.",
    curiosities: ["Não confundir com Cesareia de Filipe, ao norte, onde Pedro confessou que Jesus é o Cristo."],
    refs: [r("atos", 10, "Atos 10"), r("atos", 25, "Atos 25")],
    discoverBy: [{ book: "atos", chapter: 10 }],
  },
  {
    id: "filipos",
    name: "Filipos",
    emoji: "⛓️",
    region: "Macedônia",
    modern: "Sítio arqueológico de Filipos, Grécia",
    coords: { lat: 41.01, lng: 24.29 },
    summary: "Primeira igreja fundada por Paulo na Europa.",
    events: [
      "Conversão de Lídia, à beira do rio.",
      "Paulo e Silas presos, louvando à meia-noite.",
      "Conversão do carcereiro e de sua casa.",
    ],
    people: ["Paulo", "Silas", "Lídia", "o carcereiro", "Timóteo", "Lucas"],
    verses: [
      { ref: "Atos 16:31", text: "Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.", book: "atos", chapter: 16 },
      { ref: "Filipenses 4:4", text: "Regozijai-vos sempre no Senhor; outra vez digo: regozijai-vos.", book: "fp", chapter: 4 },
    ],
    history: "Colônia romana na Macedônia, com forte presença de veteranos do exército.",
    curiosities: ["A carta aos Filipenses é conhecida como a carta da alegria."],
    refs: [r("atos", 16, "Atos 16"), r("fp", 4, "Filipenses 4")],
    discoverBy: [{ book: "atos", chapter: 16 }, { book: "fp", chapter: 1 }],
  },
  {
    id: "tessalonica",
    name: "Tessalônica",
    emoji: "📨",
    region: "Macedônia",
    modern: "Tessalônica, Grécia",
    coords: { lat: 40.64, lng: 22.94 },
    summary: "Cidade macedônia que recebeu duas cartas de Paulo sobre esperança e a volta de Cristo.",
    events: ["Pregação de Paulo por três sábados na sinagoga.", "Tumulto e saída apressada dos missionários."],
    people: ["Paulo", "Silas", "Jasom", "Timóteo"],
    verses: [
      { ref: "1 Tessalonicenses 5:17", text: "Orai sem cessar.", book: "1ts", chapter: 5 },
      { ref: "1 Tessalonicenses 4:16", text: "O mesmo Senhor descerá do céu com alarido.", book: "1ts", chapter: 4 },
    ],
    history: "Capital da província romana da Macedônia, situada na via Egnácia.",
    curiosities: ["As cartas aos tessalonicenses estão entre os escritos mais antigos de Paulo."],
    refs: [r("atos", 17, "Atos 17"), r("1ts", 4, "1 Tessalonicenses 4")],
    discoverBy: [{ book: "atos", chapter: 17 }, { book: "1ts", chapter: 1 }],
  },
  {
    id: "bereia",
    name: "Bereia",
    emoji: "🔎",
    region: "Macedônia",
    modern: "Véria, Grécia",
    coords: { lat: 40.52, lng: 22.2 },
    summary: "Cidade dos ouvintes que examinavam diariamente as Escrituras.",
    events: ["Paulo e Silas pregam na sinagoga.", "Muitos creem depois de conferirem o ensino nas Escrituras."],
    people: ["Paulo", "Silas", "Timóteo", "Sópatro"],
    verses: [
      { ref: "Atos 17:11", text: "Receberam a palavra com toda a avidez, examinando cada dia nas Escrituras se estas coisas eram assim.", book: "atos", chapter: 17 },
    ],
    history: "Cidade macedônia menor, próxima a Tessalônica, para onde os missionários seguiram após a perseguição.",
    curiosities: ["O nome 'bereano' virou sinônimo de quem confere tudo na Bíblia."],
    refs: [r("atos", 17, "Atos 17")],
    discoverBy: [{ book: "atos", chapter: 17 }],
  },
  {
    id: "patmos",
    name: "Patmos",
    emoji: "🏝️",
    region: "Mar Egeu",
    modern: "Ilha de Patmos, Grécia",
    coords: { lat: 37.31, lng: 26.55 },
    summary: "A ilha onde João recebeu a revelação de Jesus Cristo.",
    events: ["Exílio do apóstolo João.", "Visão do Ressuscitado e das cartas às sete igrejas."],
    people: ["João"],
    verses: [
      { ref: "Apocalipse 1:9", text: "Eu, João... estava na ilha chamada Patmos, por causa da palavra de Deus.", book: "ap", chapter: 1 },
      { ref: "Apocalipse 21:5", text: "Eis que faço novas todas as coisas.", book: "ap", chapter: 21 },
    ],
    history: "Pequena ilha rochosa do Egeu, usada pelos romanos como lugar de degredo.",
    curiosities: ["É o único lugar do Apocalipse identificado como onde o livro foi recebido."],
    refs: [r("ap", 1, "Apocalipse 1")],
    discoverBy: [{ book: "ap", chapter: 1 }],
  },
  {
    id: "babilonia",
    name: "Babilônia",
    emoji: "🦁",
    region: "Mesopotâmia",
    modern: "Ruínas próximas a Hilla, Iraque",
    coords: { lat: 32.54, lng: 44.42 },
    summary: "Império que destruiu Jerusalém e levou Judá ao exílio.",
    events: [
      "Deportação de Judá e destruição do Templo.",
      "Daniel e seus amigos na corte do rei.",
      "A fornalha ardente e a cova dos leões.",
      "Retorno dos exilados no tempo de Ciro.",
    ],
    people: ["Nabucodonosor", "Daniel", "Sadraque", "Mesaque", "Abednego", "Ezequiel", "Belsazar"],
    verses: [
      { ref: "Salmos 137:1", text: "Junto aos rios de Babilônia, ali nos assentamos e choramos.", book: "sl", chapter: 137 },
      { ref: "Jeremias 29:11", text: "Porque eu bem sei os pensamentos que penso de vós... pensamentos de paz.", book: "jr", chapter: 29 },
    ],
    history: "Capital do império neobabilônico, às margens do Eufrates. Caiu diante dos persas em 539 a.C.",
    curiosities: ["No Apocalipse, 'Babilônia' aparece como símbolo de um sistema oposto a Deus."],
    refs: [r("dn", 3, "Daniel 3"), r("dn", 6, "Daniel 6"), r("jr", 29, "Jeremias 29")],
    discoverBy: [{ book: "dn", chapter: 1 }, { book: "dn", chapter: 3 }, { book: "2rs", chapter: 25 }],
  },
  {
    id: "ninive",
    name: "Nínive",
    emoji: "🐋",
    region: "Assíria",
    modern: "Ruínas em Mossul, Iraque",
    coords: { lat: 36.36, lng: 43.15 },
    summary: "A grande cidade assíria que se arrependeu com a pregação de Jonas.",
    events: ["Pregação de Jonas e arrependimento da cidade.", "Profecia de Naum sobre o seu juízo."],
    people: ["Jonas", "Naum", "o rei de Nínive"],
    verses: [
      { ref: "Jonas 3:10", text: "Viu Deus as obras deles, como se converteram do seu mau caminho.", book: "jn", chapter: 3 },
      { ref: "Jonas 4:11", text: "Não hei de eu ter compaixão da grande cidade de Nínive?", book: "jn", chapter: 4 },
    ],
    history: "Capital do império assírio, potência militar que destruiu o Reino do Norte.",
    curiosities: ["Jesus citou o arrependimento de Nínive como exemplo."],
    refs: [r("jn", 3, "Jonas 3"), r("na", 1, "Naum 1")],
    discoverBy: [{ book: "jn", chapter: 1 }, { book: "jn", chapter: 3 }],
  },
  {
    id: "ur",
    name: "Ur dos Caldeus",
    emoji: "🌙",
    region: "Mesopotâmia",
    modern: "Tell el-Muqayyar, sul do Iraque (identificação mais aceita)",
    coords: { lat: 30.96, lng: 46.1 },
    summary: "A cidade de origem de Abraão, ponto de partida da caminhada da fé.",
    events: ["Terá parte de Ur com sua família.", "Deus chama Abrão para deixar a sua terra."],
    people: ["Terá", "Abrão (Abraão)", "Sarai (Sara)", "Ló"],
    verses: [
      { ref: "Gênesis 12:1", text: "Sai da tua terra, e da tua parentela... para a terra que eu te mostrarei.", book: "gn", chapter: 12 },
      { ref: "Hebreus 11:8", text: "Pela fé Abraão, sendo chamado, obedeceu, indo para um lugar que havia de receber por herança.", book: "hb", chapter: 11 },
    ],
    history: "Importante cidade suméria com grande zigurate, situada perto do Eufrates.",
    curiosities: ["A viagem de Abraão passou por Harã antes de chegar a Canaã."],
    refs: [r("gn", 11, "Gênesis 11"), r("gn", 12, "Gênesis 12")],
    discoverBy: [{ book: "gn", chapter: 11 }, { book: "gn", chapter: 12 }],
  },
  {
    id: "carmelo",
    name: "Monte Carmelo",
    emoji: "🔥",
    region: "Norte de Israel",
    modern: "Serra do Carmelo, Haifa, Israel",
    coords: { lat: 32.73, lng: 35.05 },
    summary: "O monte do desafio de Elias contra os profetas de Baal.",
    events: ["O sacrifício consumido pelo fogo do céu.", "A oração de Elias pelo fim da seca."],
    people: ["Elias", "Acabe", "Eliseu"],
    verses: [
      { ref: "1 Reis 18:21", text: "Até quando coxeareis entre dois pensamentos?", book: "1rs", chapter: 18 },
      { ref: "1 Reis 18:39", text: "O Senhor é Deus! O Senhor é Deus!", book: "1rs", chapter: 18 },
    ],
    history: "Cadeia montanhosa junto ao Mediterrâneo, fronteira entre Israel e a Fenícia.",
    curiosities: ["Eliseu também é encontrado no Carmelo em 2 Reis."],
    refs: [r("1rs", 18, "1 Reis 18")],
    discoverBy: [{ book: "1rs", chapter: 18 }],
  },
  {
    id: "silo",
    name: "Siló",
    emoji: "⛺",
    region: "Efraim",
    modern: "Khirbet Seilun, Cisjordânia",
    coords: { lat: 32.06, lng: 35.29 },
    summary: "Onde o tabernáculo permaneceu por gerações antes do Templo.",
    events: ["Divisão da terra entre as tribos.", "Oração de Ana e nascimento de Samuel.", "Chamado do menino Samuel."],
    people: ["Josué", "Eli", "Ana", "Samuel"],
    verses: [
      { ref: "1 Samuel 3:10", text: "Fala, porque o teu servo ouve.", book: "1sm", chapter: 3 },
      { ref: "1 Samuel 1:27", text: "Por este menino orava eu; e o Senhor me concedeu a minha petição.", book: "1sm", chapter: 1 },
    ],
    history: "Centro religioso de Israel no período dos juízes, antes da monarquia.",
    curiosities: ["Jeremias usa a ruína de Siló como advertência a Jerusalém."],
    refs: [r("js", 18, "Josué 18"), r("1sm", 1, "1 Samuel 1"), r("1sm", 3, "1 Samuel 3")],
    discoverBy: [{ book: "1sm", chapter: 1 }, { book: "1sm", chapter: 3 }],
  },
  {
    id: "betel",
    name: "Betel",
    emoji: "🪜",
    region: "Efraim / Benjamim",
    modern: "Região de Beitin, Cisjordânia",
    coords: { lat: 31.93, lng: 35.22 },
    summary: "A 'casa de Deus', onde Jacó sonhou com a escada que ligava o céu à terra.",
    events: [
      "Sonho de Jacó e o voto que fez a Deus.",
      "Abraão levanta um altar nas proximidades.",
      "Jeroboão instala ali um bezerro de ouro.",
    ],
    people: ["Abraão", "Jacó", "Débora", "Samuel", "Jeroboão", "Amós"],
    verses: [
      { ref: "Gênesis 28:16", text: "Na verdade, o Senhor está neste lugar, e eu não o sabia.", book: "gn", chapter: 28 },
      { ref: "Gênesis 28:17", text: "Esta não é outra coisa senão a casa de Deus.", book: "gn", chapter: 28 },
    ],
    history: "Local de culto muito antigo nas montanhas centrais; virou santuário oficial do Reino do Norte.",
    curiosities: ["O nome significa literalmente 'casa de Deus'."],
    refs: [r("gn", 28, "Gênesis 28"), r("1rs", 12, "1 Reis 12")],
    discoverBy: [{ book: "gn", chapter: 28 }],
  },
  {
    id: "oliveiras",
    name: "Monte das Oliveiras",
    emoji: "🫒",
    region: "Jerusalém",
    modern: "Monte das Oliveiras, Jerusalém",
    coords: { lat: 31.78, lng: 35.25 },
    summary: "O monte da oração de Jesus, do Getsêmani e da ascensão.",
    events: [
      "Jesus ensina sobre os últimos tempos.",
      "Agonia e oração no Getsêmani.",
      "Ascensão de Jesus diante dos discípulos.",
    ],
    people: ["Jesus", "Pedro", "Tiago", "João", "Davi"],
    verses: [
      { ref: "Lucas 22:42", text: "Não se faça a minha vontade, mas a tua.", book: "lc", chapter: 22 },
      { ref: "Atos 1:11", text: "Este Jesus... há de vir assim como para o céu o vistes ir.", book: "atos", chapter: 1 },
    ],
    history: "Elevação a leste de Jerusalém, coberta de oliveiras, separada da cidade pelo vale do Cedrom.",
    curiosities: ["Davi subiu chorando esse monte ao fugir de Absalão."],
    refs: [r("mt", 24, "Mateus 24"), r("lc", 22, "Lucas 22"), r("atos", 1, "Atos 1")],
    discoverBy: [{ book: "lc", chapter: 22 }, { book: "atos", chapter: 1 }],
  },
  {
    id: "cana",
    name: "Caná da Galileia",
    emoji: "🍇",
    region: "Galileia",
    modern: "Kafr Kanna (identificação tradicional), Israel",
    coords: { lat: 32.75, lng: 35.34 },
    summary: "Onde Jesus realizou o primeiro sinal, transformando água em vinho.",
    events: ["A festa de casamento e o milagre do vinho.", "Cura à distância do filho de um oficial do rei."],
    people: ["Jesus", "Maria", "Natanael"],
    verses: [{ ref: "João 2:11", text: "Jesus principiou os seus sinais em Caná da Galileia.", book: "jo", chapter: 2 }],
    history: "Pequena aldeia galileia; a identificação com o sítio atual é tradicional, não definitiva.",
    curiosities: ["Natanael, um dos discípulos, era de Caná."],
    refs: [r("jo", 2, "João 2"), r("jo", 4, "João 4")],
    discoverBy: [{ book: "jo", chapter: 2 }],
  },
  {
    id: "atenas",
    name: "Atenas",
    emoji: "🏺",
    region: "Acaia (Grécia)",
    modern: "Atenas, Grécia",
    coords: { lat: 37.98, lng: 23.73 },
    summary: "Cidade dos filósofos, onde Paulo pregou no Areópago sobre o Deus desconhecido.",
    events: ["Discurso de Paulo no Areópago.", "Conversão de Dionísio e Dâmaris."],
    people: ["Paulo", "Dionísio", "Dâmaris"],
    verses: [
      { ref: "Atos 17:28", text: "Nele vivemos, e nos movemos, e existimos.", book: "atos", chapter: 17 },
    ],
    history: "Centro cultural e filosófico do mundo grego, cheia de templos e altares no primeiro século.",
    curiosities: ["Paulo citou poetas gregos para apresentar o Criador."],
    refs: [r("atos", 17, "Atos 17")],
    discoverBy: [{ book: "atos", chapter: 17 }],
  },
  {
    id: "jope",
    name: "Jope",
    emoji: "🐟",
    region: "Costa da Judeia",
    modern: "Jafa, Tel Aviv, Israel",
    coords: { lat: 32.05, lng: 34.75 },
    summary: "Porto de onde Jonas fugiu e onde Pedro teve a visão que abriu a missão aos gentios.",
    events: ["Jonas embarca para Társis.", "Ressurreição de Dorcas.", "Visão do lençol com animais."],
    people: ["Jonas", "Pedro", "Dorcas (Tabita)", "Simão, o curtidor"],
    verses: [
      { ref: "Atos 10:15", text: "Não faças tu comum ao que Deus purificou.", book: "atos", chapter: 10 },
    ],
    history: "Antigo porto natural da costa israelita, usado desde o tempo de Salomão para receber madeira do Líbano.",
    curiosities: ["A cidade liga duas histórias sobre o alcance da graça: Jonas e Pedro."],
    refs: [r("jn", 1, "Jonas 1"), r("atos", 9, "Atos 9"), r("atos", 10, "Atos 10")],
    discoverBy: [{ book: "jn", chapter: 1 }, { book: "atos", chapter: 9 }],
  },
  {
    id: "berseba",
    name: "Berseba",
    emoji: "🏜️",
    region: "Neguebe",
    modern: "Beer Sheva, Israel",
    coords: { lat: 31.25, lng: 34.79 },
    summary: "Marco sul da terra de Israel e lugar de poços e alianças dos patriarcas.",
    events: ["Aliança de Abraão com Abimeleque.", "Deus aparece a Isaque e a Jacó.", "Elias descansa a caminho de Horebe."],
    people: ["Abraão", "Isaque", "Jacó", "Agar", "Elias"],
    verses: [
      { ref: "Gênesis 21:33", text: "E invocou ali o nome do Senhor, Deus eterno.", book: "gn", chapter: 21 },
    ],
    history: "Cidade na borda do deserto do Neguebe; a expressão 'de Dã a Berseba' descrevia toda a extensão de Israel.",
    curiosities: ["O nome está ligado a 'poço do juramento'."],
    refs: [r("gn", 21, "Gênesis 21"), r("gn", 26, "Gênesis 26"), r("1rs", 19, "1 Reis 19")],
    discoverBy: [{ book: "gn", chapter: 21 }],
  },
  {
    id: "nebo",
    name: "Monte Nebo",
    emoji: "🌄",
    region: "Moabe",
    modern: "Monte Nebo, Jordânia",
    coords: { lat: 31.77, lng: 35.73 },
    summary: "De onde Moisés viu a Terra Prometida antes de morrer.",
    events: ["Moisés contempla Canaã.", "Morte e sepultamento de Moisés em lugar desconhecido."],
    people: ["Moisés", "Josué"],
    verses: [
      { ref: "Deuteronômio 34:4", text: "Esta é a terra que jurei a Abraão... Fiz que a visses com os teus olhos.", book: "dt", chapter: 34 },
    ],
    history: "Elevação a leste do mar Morto, na região de Moabe, com ampla vista sobre o vale do Jordão.",
    curiosities: ["O texto afirma que ninguém soube onde Moisés foi sepultado."],
    refs: [r("dt", 34, "Deuteronômio 34")],
    discoverBy: [{ book: "dt", chapter: 34 }],
  },
  {
    id: "mar-morto",
    name: "Mar Morto",
    emoji: "🧂",
    region: "Vale do Jordão",
    modern: "Mar Morto, entre Israel e a Jordânia",
    coords: { lat: 31.5, lng: 35.47 },
    summary: "O grande lago salgado, próximo ao território de Sodoma e Gomorra e aos refúgios de Davi.",
    events: [
      "Região das cidades do vale, no relato de Gênesis.",
      "Davi se esconde nas cavernas de En-Gedi.",
      "Visão de Ezequiel sobre águas que curam o mar.",
    ],
    people: ["Ló", "Abraão", "Davi", "Ezequiel"],
    verses: [
      { ref: "Ezequiel 47:9", text: "Tudo viverá para onde quer que chegar este rio.", book: "ez", chapter: 47 },
    ],
    history: "Ponto mais baixo da superfície terrestre; suas águas extremamente salgadas não sustentam vida.",
    curiosities: ["Chamado na Bíblia de mar Salgado e mar da Planície."],
    refs: [r("gn", 19, "Gênesis 19"), r("1sm", 24, "1 Samuel 24"), r("ez", 47, "Ezequiel 47")],
    discoverBy: [{ book: "gn", chapter: 19 }, { book: "1sm", chapter: 24 }],
  },
];

export function placeById(id: string): BiblePlace | undefined {
  return BIBLE_PLACES.find((p) => p.id === id);
}

function key(book: string, chapter: number) {
  return `${book}:${chapter}`;
}

/** Um local está descoberto se for `core` ou se o usuário leu um dos capítulos ligados a ele. */
export function isPlaceDiscovered(place: BiblePlace, readSet: Set<string>): boolean {
  if (place.core) return true;
  return (place.discoverBy ?? []).some((d) => readSet.has(key(d.book, d.chapter)));
}

/** Só conta os locais que exigem leitura — os `core` não são "conquista". */
export function countDiscoveredPlaces(readSet: Set<string>): number {
  return BIBLE_PLACES.filter((p) => !p.core && isPlaceDiscovered(p, readSet)).length;
}

export function unlockableePlacesTotal(): number {
  return BIBLE_PLACES.filter((p) => !p.core).length;
}

/** Projeção equiretangular simples para o SVG do mapa (viewBox 0 0 1000 640). */
export const MAP_BOUNDS = { minLng: 10, maxLng: 48, minLat: 26, maxLat: 43 };

export function projectPlace(coords: { lat: number; lng: number }): { x: number; y: number } {
  const { minLng, maxLng, minLat, maxLat } = MAP_BOUNDS;
  const x = ((coords.lng - minLng) / (maxLng - minLng)) * 1000;
  const y = ((maxLat - coords.lat) / (maxLat - minLat)) * 640;
  return { x, y };
}