import type { BibleRef } from "@/lib/atlas-shared";

export type BibleJudge = {
  id: string;
  name: string;
  emoji: string;
  tribe: string;
  /** o que o texto bíblico informa sobre o período, quando informa */
  period: string;
  oppressor: string;
  summary: string;
  context: string;
  role: string;
  story: string[];
  places: string[];
  people: string[];
  refs: BibleRef[];
  curiosities: string[];
  /** distingue o que está no texto do que é leitura/tradição posterior */
  traditionNote?: string;
};

const r = (book: string, chapter: number, label: string): BibleRef => ({ book, chapter, label });

export const BIBLE_JUDGES: BibleJudge[] = [
  {
    id: "otniel",
    name: "Otniel",
    emoji: "🗡️",
    tribe: "Judá",
    period: "O texto diz que a terra teve paz quarenta anos.",
    oppressor: "Cusã-Risataim, rei da Mesopotâmia",
    summary: "O primeiro juiz levantado por Deus depois da morte de Josué.",
    context:
      "Após a morte de Josué, o povo serviu a outros deuses e foi entregue nas mãos de um rei da Mesopotâmia por oito anos.",
    role: "Foi levantado pelo Senhor como libertador; o Espírito do Senhor veio sobre ele e ele julgou Israel.",
    story: [
      "Era filho de Quenaz, irmão mais novo de Calebe.",
      "Havia conquistado Quiriate-Sefer e recebido Acsa, filha de Calebe, por esposa.",
      "Clamando o povo ao Senhor, Otniel os libertou e a terra teve descanso.",
    ],
    places: ["Debir (Quiriate-Sefer)", "Judá"],
    people: ["Calebe", "Acsa", "Cusã-Risataim"],
    refs: [r("jz", 1, "Juízes 1"), r("jz", 3, "Juízes 3"), r("js", 15, "Josué 15")],
    curiosities: ["É o único juiz da tribo de Judá citado no livro."],
  },
  {
    id: "eude",
    name: "Eúde",
    emoji: "🛡️",
    tribe: "Benjamim",
    period: "O texto diz que a terra teve paz oitenta anos.",
    oppressor: "Eglom, rei de Moabe",
    summary: "O juiz canhoto que libertou Israel do domínio moabita.",
    context: "Israel voltou a fazer o mal e serviu a Eglom, rei de Moabe, por dezoito anos.",
    role: "Levou o tributo a Eglom e, num encontro reservado, o matou; depois convocou Israel e tomou os vaus do Jordão.",
    story: [
      "Era canhoto e escondeu uma espada de dois gumes na coxa direita.",
      "Após a morte de Eglom, tocou a trombeta na montanha de Efraim.",
      "Israel derrotou Moabe e teve um longo período de paz.",
    ],
    places: ["Jericó (cidade das palmeiras)", "Moabe", "Vaus do Jordão", "Montanha de Efraim"],
    people: ["Eglom"],
    refs: [r("jz", 3, "Juízes 3")],
    curiosities: ["O texto destaca duas vezes que ele era canhoto, detalhe importante para a narrativa."],
  },
  {
    id: "sangar",
    name: "Sangar",
    emoji: "🐂",
    tribe: "Não informada no texto",
    period: "Não informado.",
    oppressor: "Filisteus",
    summary: "Juiz citado em um único versículo, que feriu seiscentos filisteus.",
    context: "Período de pressão filisteia sobre Israel, entre os relatos de Eúde e de Débora.",
    role: "Livrou Israel ferindo seiscentos filisteus com uma aguilhada de bois.",
    story: [
      "É apresentado como filho de Anate.",
      "Seu nome reaparece no cântico de Débora, marcando um tempo de estradas desertas.",
    ],
    places: ["Território filisteu"],
    people: ["Anate (pai)", "Débora (cântico)"],
    refs: [r("jz", 3, "Juízes 3"), r("jz", 5, "Juízes 5")],
    curiosities: ["A aguilhada era uma vara usada para conduzir bois, não uma arma de guerra."],
    traditionNote: "Tudo o que a Bíblia informa sobre Sangar está em dois versículos; qualquer detalhe além disso é tradição posterior.",
  },
  {
    id: "debora",
    name: "Débora",
    emoji: "🌿",
    tribe: "Efraim (onde julgava)",
    period: "O texto diz que a terra teve paz quarenta anos.",
    oppressor: "Jabim, rei de Canaã, e seu general Sísera",
    summary: "Profetisa e juíza que julgava Israel debaixo de uma palmeira e conduziu a vitória sobre Sísera.",
    context: "Israel foi oprimido vinte anos por Jabim, que possuía novecentos carros de ferro.",
    role: "Julgava o povo e transmitia a palavra do Senhor; convocou Baraque para a batalha e o acompanhou.",
    story: [
      "Assentava-se debaixo da palmeira de Débora, entre Ramá e Betel.",
      "Chamou Baraque para reunir dez mil homens no monte Tabor.",
      "O exército de Sísera foi desbaratado junto ao ribeiro Quisom.",
      "Sísera foi morto por Jael, na tenda dela.",
      "Débora e Baraque entoaram um cântico de vitória.",
    ],
    places: ["Palmeira entre Ramá e Betel", "Monte Tabor", "Ribeiro Quisom", "Hazor"],
    people: ["Baraque", "Sísera", "Jael", "Jabim", "Lapidote"],
    refs: [r("jz", 4, "Juízes 4"), r("jz", 5, "Juízes 5")],
    curiosities: ["É a única mulher chamada de juíza no livro e também é chamada de profetisa."],
  },
  {
    id: "gideao",
    name: "Gideão",
    emoji: "🔥",
    tribe: "Manassés",
    period: "O texto diz que a terra teve paz quarenta anos.",
    oppressor: "Midianitas, amalequitas e povos do oriente",
    summary: "O homem que se via como o menor e foi chamado de valente para libertar Israel com trezentos homens.",
    context: "Israel se escondia em cavernas por causa das invasões de Midiã, que destruíam as colheitas.",
    role: "Derrubou o altar de Baal, reuniu o povo e venceu Midiã com um exército reduzido por Deus.",
    story: [
      "O anjo do Senhor o encontrou malhando trigo no lagar.",
      "Pediu o sinal do velo de lã, duas vezes.",
      "Deus reduziu o exército de 32 mil para 300 homens.",
      "A vitória veio com trombetas, cântaros e tochas.",
      "Recusou reinar, mas fez um éfode que se tornou tropeço para o povo.",
    ],
    places: ["Ofra", "Vale de Jezreel", "Fonte de Harode", "Jordão"],
    people: ["Joás (pai)", "Purá", "Zeba e Zalmuna", "Orebe e Zeebe", "Abimeleque (filho)"],
    refs: [r("jz", 6, "Juízes 6"), r("jz", 7, "Juízes 7"), r("jz", 8, "Juízes 8"), r("hb", 11, "Hebreus 11")],
    curiosities: ["Também é chamado de Jerubaal, nome ligado à derrubada do altar de Baal."],
  },
  {
    id: "abimeleque",
    name: "Abimeleque",
    emoji: "⚠️",
    tribe: "Manassés (filho de Gideão)",
    period: "Dominou Israel por três anos.",
    oppressor: "—",
    summary: "Filho de Gideão que se fez rei em Siquém; o texto não o apresenta como libertador enviado por Deus.",
    context: "Após a morte de Gideão, Israel voltou a servir aos baalins.",
    role: "Tomou o poder pela força, matando os irmãos; seu governo terminou em conflito e morte.",
    story: [
      "Foi feito rei pelos homens de Siquém.",
      "Jotão, o irmão que escapou, proclamou a parábola das árvores no monte Gerizim.",
      "Morreu em Tebes, ferido por uma pedra de moinho lançada por uma mulher.",
    ],
    places: ["Siquém", "Monte Gerizim", "Tebes"],
    people: ["Gideão (pai)", "Jotão", "os homens de Siquém"],
    refs: [r("jz", 9, "Juízes 9")],
    curiosities: ["A parábola de Jotão é uma das mais antigas fábulas registradas na Bíblia."],
    traditionNote:
      "Abimeleque aparece na sequência do livro de Juízes, mas o texto não diz que o Senhor o levantou como libertador — ele tomou o poder por conta própria.",
  },
  {
    id: "tola",
    name: "Tola",
    emoji: "🕊️",
    tribe: "Issacar",
    period: "Julgou Israel vinte e três anos.",
    oppressor: "Não informado.",
    summary: "Juiz que se levantou depois de Abimeleque para livrar Israel.",
    context: "Período de instabilidade após o governo violento de Abimeleque.",
    role: "Julgou Israel e habitou em Samir, na montanha de Efraim.",
    story: ["Era filho de Puá, filho de Dodo.", "O texto registra seu tempo de juízo, sua cidade e sua morte."],
    places: ["Samir", "Montanha de Efraim"],
    people: ["Puá (pai)"],
    refs: [r("jz", 10, "Juízes 10")],
    curiosities: ["Faz parte dos chamados 'juízes menores', citados em poucos versículos."],
  },
  {
    id: "jair",
    name: "Jair",
    emoji: "🐴",
    tribe: "Gileade",
    period: "Julgou Israel vinte e dois anos.",
    oppressor: "Não informado.",
    summary: "Juiz gileadita cujos trinta filhos governavam trinta cidades.",
    context: "Continuidade do período dos juízes na região a leste do Jordão.",
    role: "Julgou Israel em Gileade.",
    story: ["Tinha trinta filhos que cavalgavam trinta jumentos.", "As cidades deles eram chamadas Havote-Jair."],
    places: ["Gileade", "Havote-Jair", "Camom"],
    people: ["Seus trinta filhos"],
    refs: [r("jz", 10, "Juízes 10")],
    curiosities: ["O nome das cidades significa 'aldeias de Jair'."],
  },
  {
    id: "jefte",
    name: "Jefté",
    emoji: "⚔️",
    tribe: "Gileade / Manassés",
    period: "Julgou Israel seis anos.",
    oppressor: "Amonitas",
    summary: "Rejeitado pelos irmãos, foi chamado de volta para liderar Israel contra Amom.",
    context: "Israel serviu a deuses estrangeiros e foi oprimido pelos amonitas por dezoito anos.",
    role: "Foi feito cabeça de Gileade, negociou com o rei de Amom e venceu a guerra.",
    story: [
      "Era filho de uma mulher prostituta e foi expulso da casa paterna.",
      "Enviou mensageiros ao rei amonita, recorrendo à história do Êxodo.",
      "Fez um voto ao Senhor antes da batalha, que resultou em grande dor pessoal envolvendo sua filha.",
      "Houve depois um conflito com a tribo de Efraim, marcado pela palavra 'chibolete'.",
    ],
    places: ["Gileade", "Terra de Tobe", "Mispa", "Vaus do Jordão"],
    people: ["A filha de Jefté", "os anciãos de Gileade", "o rei dos amonitas"],
    refs: [r("jz", 11, "Juízes 11"), r("jz", 12, "Juízes 12"), r("hb", 11, "Hebreus 11")],
    curiosities: ["Jefté é citado entre os heróis da fé em Hebreus 11."],
    traditionNote:
      "O sentido exato do voto de Jefté é discutido há séculos entre intérpretes; o texto bíblico narra o fato sem explicá-lo.",
  },
  {
    id: "ibsa",
    name: "Ibsã",
    emoji: "🏘️",
    tribe: "Belém",
    period: "Julgou Israel sete anos.",
    oppressor: "Não informado.",
    summary: "Juiz de Belém, com trinta filhos e trinta filhas.",
    context: "Sequência dos juízes menores, após Jefté.",
    role: "Julgou Israel e organizou casamentos fora do seu clã.",
    story: ["Casou suas trinta filhas fora e trouxe trinta noras de fora para os filhos."],
    places: ["Belém"],
    people: ["Seus sessenta filhos e filhas"],
    refs: [r("jz", 12, "Juízes 12")],
    curiosities: ["O texto não esclarece se essa Belém é a de Judá ou a de Zebulom."],
  },
  {
    id: "elom",
    name: "Elom",
    emoji: "🌾",
    tribe: "Zebulom",
    period: "Julgou Israel dez anos.",
    oppressor: "Não informado.",
    summary: "Juiz zebulonita citado brevemente no livro de Juízes.",
    context: "Continuidade do período dos juízes.",
    role: "Julgou Israel por dez anos.",
    story: ["Foi sepultado em Aijalom, na terra de Zebulom."],
    places: ["Aijalom (Zebulom)"],
    people: [],
    refs: [r("jz", 12, "Juízes 12")],
    curiosities: ["Sobre ele o texto registra apenas duas informações: o tempo de juízo e o sepultamento."],
  },
  {
    id: "abdom",
    name: "Abdom",
    emoji: "🐎",
    tribe: "Efraim (Piratom)",
    period: "Julgou Israel oito anos.",
    oppressor: "Não informado.",
    summary: "Juiz de Piratom, com quarenta filhos e trinta netos.",
    context: "Último dos juízes menores antes de Sansão.",
    role: "Julgou Israel por oito anos.",
    story: ["Seus filhos e netos cavalgavam setenta jumentos, sinal de prosperidade."],
    places: ["Piratom", "Montanha dos amalequitas"],
    people: ["Hilel (pai)"],
    refs: [r("jz", 12, "Juízes 12")],
    curiosities: ["A menção aos jumentos indicava status na época."],
  },
  {
    id: "sansao",
    name: "Sansão",
    emoji: "🦁",
    tribe: "Dã",
    period: "Julgou Israel vinte anos.",
    oppressor: "Filisteus",
    summary: "O nazireu de força extraordinária, cuja história mistura vitória, queda e redenção final.",
    context: "Israel esteve quarenta anos sob domínio filisteu.",
    role: "Foi consagrado nazireu desde o ventre e julgou Israel enfrentando os filisteus.",
    story: [
      "Seu nascimento foi anunciado por um anjo aos pais.",
      "Despedaçou um leão jovem e propôs um enigma nas bodas.",
      "Enfrentou os filisteus em episódios sucessivos de conflito.",
      "Foi traído por Dalila, perdeu o cabelo e a força, e foi preso e cegado.",
      "No fim, orou ao Senhor e derrubou o templo de Dagom.",
    ],
    places: ["Zorá", "Estaol", "Timnate", "Gaza", "Vale de Soreque"],
    people: ["Manoá (pai)", "Dalila", "os príncipes dos filisteus"],
    refs: [r("jz", 13, "Juízes 13"), r("jz", 14, "Juízes 14"), r("jz", 15, "Juízes 15"), r("jz", 16, "Juízes 16"), r("hb", 11, "Hebreus 11")],
    curiosities: ["O voto de nazireu incluía não cortar o cabelo, não beber vinho e não tocar em corpo morto."],
  },
];

export function judgeById(id: string): BibleJudge | undefined {
  return BIBLE_JUDGES.find((j) => j.id === id);
}