export interface ResumoBiblico {
  id: string;
  name: string;
  testament: "old" | "new";
  author: string;
  context: string;
  theme: string;
  purpose: string;
  teachings: string[];
  keyVerses: string[];
  summary: string;
  facts: string[];
}

export const resumosBiblicos: ResumoBiblico[] = [
  { id: "gn", name: "Gênesis", testament: "old", author: "Tradicionalmente atribuído a Moisés", context: "Escrito por volta de 1450–1410 a.C., narra desde a criação até a morte de José no Egito.", theme: "Criação, queda, aliança e origens do povo de Deus", purpose: "Revelar as origens do mundo, da humanidade, do pecado e da aliança de Deus com os patriarcas.", teachings: ["Deus é o Criador soberano de todas as coisas", "O pecado entra no mundo pela desobediência", "Deus chama um povo para abençoar as nações", "A fé de Abraão como modelo de relacionamento com Deus"], keyVerses: ["Gênesis 1:1", "Gênesis 3:15", "Gênesis 12:2-3", "Gênesis 50:20"], summary: "Explica a criação do mundo, a queda do homem, o dilúvio, os patriarcas e a aliança de Deus com Abraão, Isaque, Jacó e José.", facts: ["É o primeiro livro da Torá", "Cobre o maior período de tempo de qualquer livro bíblico", "Inclui as primeiras profecias messiânicas"] },
  { id: "ex", name: "Êxodo", testament: "old", author: "Tradicionalmente atribuído a Moisés", context: "Israel escravizado no Egito por cerca de 400 anos é libertado por Deus através de Moisés.", theme: "Redenção, libertação e aliança", purpose: "Mostrar como Deus liberta seu povo da escravidão e estabelece com ele uma aliança.", teachings: ["Deus ouve o clamor dos oprimidos", "A salvação vem pelo sangue do cordeiro", "A obediência à Lei reflete o caráter de Deus", "Deus habita no meio de seu povo"], keyVerses: ["Êxodo 3:14", "Êxodo 14:14", "Êxodo 20:1-17"], summary: "Narra a libertação dos israelitas do Egito, a travessia do Mar Vermelho, a entrega da Lei no Sinai e a construção do Tabernáculo.", facts: ["Contém os Dez Mandamentos", "Apresenta as dez pragas do Egito", "Institui a Páscoa judaica"] },
  { id: "lv", name: "Levítico", testament: "old", author: "Tradicionalmente atribuído a Moisés", context: "Escrito durante a permanência de Israel no Sinai, após o êxodo do Egito.", theme: "Santidade e adoração", purpose: "Ensinar Israel a adorar e viver diante de um Deus santo.", teachings: ["Deus é santo e exige santidade", "O sacrifício é necessário para o perdão", "A vida cotidiana deve refletir consagração", "Há diferença entre o sagrado e o profano"], keyVerses: ["Levítico 11:44", "Levítico 17:11", "Levítico 19:18"], summary: "Apresenta as leis sobre sacrifícios, sacerdócio, pureza ritual e festas, ensinando como o povo deve se aproximar de Deus.", facts: ["Tem o foco mais litúrgico da Torá", "Estabelece o Dia da Expiação (Yom Kippur)", "Apresenta o ano do jubileu"] },
  { id: "nm", name: "Números", testament: "old", author: "Tradicionalmente atribuído a Moisés", context: "Cobre cerca de 40 anos de peregrinação de Israel no deserto.", theme: "Peregrinação, fidelidade e incredulidade", purpose: "Mostrar como Deus guia, disciplina e preserva seu povo até a Terra Prometida.", teachings: ["A incredulidade traz consequências", "Deus é fiel apesar da fraqueza humana", "A liderança espiritual exige humildade", "Deus prepara seu povo para a herança"], keyVerses: ["Números 6:24-26", "Números 14:18", "Números 23:19"], summary: "Relata os censos, a rebelião do povo, os 40 anos no deserto e a preparação para entrar em Canaã.", facts: ["O nome vem dos censos do povo", "Inclui a história de Balaão e a jumenta", "Apresenta a bênção sacerdotal mais conhecida"] },
  { id: "dt", name: "Deuteronômio", testament: "old", author: "Tradicionalmente atribuído a Moisés", context: "Últimos discursos de Moisés nas planícies de Moabe, antes da entrada em Canaã.", theme: "Aliança renovada e obediência", purpose: "Renovar a aliança com a nova geração e exortá-la à obediência.", teachings: ["Amar a Deus de todo o coração", "A obediência traz bênção, a rebeldia traz maldição", "A Palavra deve ser ensinada aos filhos", "Deus é único e soberano"], keyVerses: ["Deuteronômio 6:4-5", "Deuteronômio 30:19", "Deuteronômio 31:6"], summary: "Recapitula a Lei, renova a aliança e prepara Israel para conquistar a Terra Prometida sob a liderança de Josué.", facts: ["Significa 'segunda lei'", "Contém o Shemá, oração central do judaísmo", "É o livro mais citado por Jesus"] },
  { id: "js", name: "Josué", testament: "old", author: "Tradicionalmente atribuído a Josué", context: "Conquista de Canaã após a morte de Moisés, por volta de 1400 a.C.", theme: "Conquista e cumprimento das promessas", purpose: "Mostrar como Deus cumpre suas promessas dando a terra ao seu povo.", teachings: ["Deus é fiel às suas promessas", "A vitória vem pela fé e obediência", "Sem santidade não há vitória duradoura", "É preciso escolher servir a Deus"], keyVerses: ["Josué 1:9", "Josué 24:15"], summary: "Relata a travessia do Jordão, a queda de Jericó, a conquista de Canaã e a divisão da terra entre as tribos.", facts: ["Inclui o sol parado em Gibeão", "Apresenta o muro de Jericó caindo", "Encerra com a aliança em Siquém"] },
  { id: "jz", name: "Juízes", testament: "old", author: "Tradicionalmente atribuído a Samuel", context: "Período entre Josué e a monarquia, marcado por ciclos de pecado e libertação.", theme: "Apostasia, juízo e misericórdia", purpose: "Mostrar a necessidade de um rei justo diante da rebeldia do povo.", teachings: ["O pecado leva à escravidão", "Deus levanta libertadores", "A misericórdia divina é inesgotável", "Cada um fazia o que parecia reto aos seus olhos"], keyVerses: ["Juízes 2:16", "Juízes 21:25"], summary: "Narra os ciclos de pecado, opressão, clamor e libertação por meio dos juízes, como Débora, Gideão e Sansão.", facts: ["Apresenta 12 juízes principais", "Inclui a história de Sansão e Dalila", "Marca um período de caos espiritual"] },
  { id: "rt", name: "Rute", testament: "old", author: "Tradicionalmente atribuído a Samuel", context: "Período dos juízes, em Belém de Judá.", theme: "Lealdade, redenção e providência", purpose: "Mostrar a providência divina e a inclusão dos gentios no plano de Deus.", teachings: ["A fidelidade é recompensada", "Deus age através do cotidiano", "O resgatador prefigura Cristo", "Deus inclui os estrangeiros na sua aliança"], keyVerses: ["Rute 1:16", "Rute 2:12"], summary: "Conta a história de Rute, a moabita, que se torna bisavó do rei Davi através de Boaz, seu resgatador.", facts: ["Rute é antepassada de Jesus", "Boaz é tipo do Redentor", "É lido na festa judaica de Shavuot"] },
  { id: "1sm", name: "1 Samuel", testament: "old", author: "Tradicionalmente atribuído a Samuel, Natã e Gade", context: "Transição entre os juízes e a monarquia em Israel.", theme: "Transição para a monarquia", purpose: "Narrar o surgimento do reino e o início da realeza em Israel.", teachings: ["A obediência é melhor que o sacrifício", "Deus vê o coração, não a aparência", "A rejeição da palavra de Deus traz queda", "A unção divina capacita o servo"], keyVerses: ["1 Samuel 15:22", "1 Samuel 16:7"], summary: "Apresenta Samuel, a unção de Saul como rei, sua queda e a ascensão de Davi.", facts: ["Davi vence Golias com uma funda", "Saul é o primeiro rei de Israel", "Samuel é o último dos juízes"] },
  { id: "2sm", name: "2 Samuel", testament: "old", author: "Tradicionalmente atribuído a Natã e Gade", context: "Reinado de Davi sobre Judá e depois sobre todo Israel.", theme: "Reinado de Davi e aliança davídica", purpose: "Mostrar o estabelecimento do reino sob Davi e a promessa messiânica.", teachings: ["Deus exalta o humilde de coração", "O pecado traz consequências mesmo aos perdoados", "Deus é fiel à sua aliança", "A liderança exige integridade"], keyVerses: ["2 Samuel 7:16", "2 Samuel 22:31"], summary: "Relata o reinado de Davi, suas vitórias, seu pecado com Bate-Seba e a aliança eterna feita por Deus com sua casa.", facts: ["Contém a aliança davídica", "Inclui o pecado com Bate-Seba", "Davi escreveu muitos salmos nesse período"] },
  { id: "1rs", name: "1 Reis", testament: "old", author: "Tradicionalmente atribuído a Jeremias", context: "Reinado de Salomão e divisão do reino entre Norte (Israel) e Sul (Judá).", theme: "Esplendor, divisão e idolatria", purpose: "Mostrar como a infidelidade leva à divisão e queda do reino.", teachings: ["A sabedoria vem de Deus", "A idolatria destrói reinos", "Profetas chamam o povo ao arrependimento", "Riqueza sem temor de Deus corrompe"], keyVerses: ["1 Reis 3:9", "1 Reis 18:21"], summary: "Narra a construção do templo por Salomão, a divisão do reino e os ministérios de Elias contra Acabe e Jezabel.", facts: ["Salomão construiu o primeiro templo", "Elias enfrentou os profetas de Baal", "Reino dividiu-se em 931 a.C."] },
  { id: "2rs", name: "2 Reis", testament: "old", author: "Tradicionalmente atribuído a Jeremias", context: "Declínio dos reinos do Norte e do Sul até os exílios assírio e babilônico.", theme: "Queda, exílio e juízo divino", purpose: "Explicar a destruição dos reinos como consequência da infidelidade à aliança.", teachings: ["Deus julga a infidelidade", "Reformas espirituais trazem renovo", "O exílio não anula a promessa", "Profetas anunciam esperança no juízo"], keyVerses: ["2 Reis 17:13", "2 Reis 22:8"], summary: "Continua a história dos reis, narrando o ministério de Eliseu, a queda de Samaria em 722 a.C. e de Jerusalém em 586 a.C.", facts: ["Eliseu sucedeu Elias", "Samaria caiu para a Assíria", "Jerusalém foi destruída por Nabucodonosor"] },
  { id: "1cr", name: "1 Crônicas", testament: "old", author: "Tradicionalmente atribuído a Esdras", context: "Escrito após o exílio babilônico, para a comunidade restaurada.", theme: "Linhagem davídica e adoração", purpose: "Reafirmar a identidade do povo de Deus e a centralidade da adoração.", teachings: ["Deus preserva sua promessa a Davi", "A adoração é o coração da vida do povo", "Deus age na história", "A herança espiritual é fundamental"], keyVerses: ["1 Crônicas 16:11", "1 Crônicas 29:11"], summary: "Apresenta genealogias desde Adão e narra o reinado de Davi com foco na arca e na preparação do templo.", facts: ["Começa com longas genealogias", "Foca no reinado positivo de Davi", "Destaca a organização do culto"] },
  { id: "2cr", name: "2 Crônicas", testament: "old", author: "Tradicionalmente atribuído a Esdras", context: "Reinado de Salomão à queda de Jerusalém, com olhar pós-exílico.", theme: "Templo, reis de Judá e fidelidade a Deus", purpose: "Mostrar que a bênção depende da fidelidade ao Senhor e ao seu templo.", teachings: ["A oração humilde traz cura", "Reformas trazem avivamento", "Deus é fiel mesmo no juízo", "O templo é símbolo da presença de Deus"], keyVerses: ["2 Crônicas 7:14", "2 Crônicas 16:9"], summary: "Narra a construção do templo, os reis de Judá, suas reformas e o exílio na Babilônia.", facts: ["Destaca reis reformadores como Ezequias e Josias", "Encerra com o decreto de Ciro", "Enfatiza a oração e o arrependimento"] },
  { id: "ed", name: "Esdras", testament: "old", author: "Tradicionalmente atribuído a Esdras", context: "Retorno dos judeus do exílio babilônico (a partir de 538 a.C.).", theme: "Restauração espiritual e do templo", purpose: "Narrar o retorno do exílio e a reconstrução do templo e do culto.", teachings: ["Deus move líderes para cumprir sua vontade", "A Palavra é a base da renovação", "A pureza espiritual exige separação do pecado", "A oração precede a ação"], keyVerses: ["Esdras 7:10"], summary: "Conta o retorno dos judeus sob Zorobabel e Esdras, a reconstrução do templo e a reforma espiritual do povo.", facts: ["Ciro permitiu o retorno", "Templo reconstruído em 516 a.C.", "Esdras era sacerdote e escriba"] },
  { id: "ne", name: "Neemias", testament: "old", author: "Tradicionalmente atribuído a Neemias", context: "Reconstrução dos muros de Jerusalém por volta de 445 a.C.", theme: "Reconstrução e renovação da aliança", purpose: "Mostrar como liderança, oração e ação restauram a comunidade do povo de Deus.", teachings: ["A oração precede a ação", "A obra de Deus enfrenta oposição", "Liderança exige coragem", "A Palavra reaviva o povo"], keyVerses: ["Neemias 1:11", "Neemias 8:10"], summary: "Narra a reconstrução dos muros de Jerusalém sob Neemias e a renovação espiritual liderada por Esdras.", facts: ["Muros reconstruídos em 52 dias", "Esdras leu a Lei publicamente", "Encerra o Antigo Testamento histórico"] },
  { id: "et", name: "Ester", testament: "old", author: "Autor desconhecido (talvez Mordecai)", context: "Comunidade judaica na Pérsia, durante o reinado de Xerxes (Assuero).", theme: "Providência divina e libertação", purpose: "Mostrar como Deus preserva seu povo, mesmo quando seu nome não aparece.", teachings: ["Deus age nos bastidores", "Coragem é fruto da fé", "Deus levanta pessoas para tempos específicos", "A oração e o jejum movem situações"], keyVerses: ["Ester 4:14"], summary: "Conta como Ester se tornou rainha da Pérsia e salvou seu povo de um decreto de extermínio.", facts: ["Único livro que não menciona Deus diretamente", "Origem da festa de Purim", "Mordecai era primo de Ester"] },
  { id: "job", name: "Jó", testament: "old", author: "Autor desconhecido", context: "Provavelmente um dos livros mais antigos da Bíblia, ambientado na terra de Uz.", theme: "Sofrimento, soberania e fé", purpose: "Refletir sobre o sofrimento do justo e a soberania de Deus.", teachings: ["O justo também sofre", "Deus é soberano e sábio", "A fé brilha na dor", "Nem todo sofrimento é castigo"], keyVerses: ["Jó 1:21", "Jó 19:25", "Jó 42:5"], summary: "Narra o sofrimento de Jó, os debates com seus amigos e o encontro restaurador com Deus.", facts: ["Considerado obra-prima poética", "Satanás aparece diante de Deus", "Jó é restaurado em dobro"] },
  { id: "sl", name: "Salmos", testament: "old", author: "Davi, Asafe, filhos de Coré, Moisés e outros", context: "Composto ao longo de séculos, é o livro de orações e cânticos de Israel.", theme: "Adoração, oração e louvor", purpose: "Ensinar a expressar toda a vida espiritual diante de Deus em oração e louvor.", teachings: ["Deus é refúgio em todo tempo", "A oração abrange toda emoção humana", "O louvor transforma o coração", "A Palavra é luz para o caminho"], keyVerses: ["Salmos 23:1", "Salmos 91:1-2", "Salmos 119:105"], summary: "Coleção de 150 cânticos e orações que expressam louvor, lamento, confissão, gratidão e esperança messiânica.", facts: ["É o livro mais longo da Bíblia", "Salmo 119 é o capítulo mais longo", "Salmos messiânicos apontam para Cristo"] },
  { id: "pv", name: "Provérbios", testament: "old", author: "Salomão, Agur, Lemuel e outros sábios", context: "Coletânea de sabedoria prática para a vida cotidiana.", theme: "Sabedoria prática e temor do Senhor", purpose: "Ensinar a viver com sabedoria, justiça e temor a Deus.", teachings: ["O temor do Senhor é o princípio da sabedoria", "As palavras têm poder de vida e morte", "A diligência produz fruto", "Companhia influencia o caráter"], keyVerses: ["Provérbios 1:7", "Provérbios 3:5-6", "Provérbios 22:6"], summary: "Coleção de ditos sábios sobre conduta, família, trabalho, justiça e relacionamento com Deus.", facts: ["Provérbios 31 descreve a mulher virtuosa", "Salomão escreveu a maior parte", "Inspira ética cristã prática"] },
  { id: "ec", name: "Eclesiastes", testament: "old", author: "Tradicionalmente atribuído a Salomão", context: "Reflexão filosófica sobre o sentido da vida 'debaixo do sol'.", theme: "O sentido da vida e o temor de Deus", purpose: "Mostrar a vaidade da vida sem Deus e a importância de temê-Lo.", teachings: ["Tudo neste mundo é passageiro", "Há tempo para todas as coisas", "Sem Deus, tudo é vaidade", "Teme a Deus e guarda seus mandamentos"], keyVerses: ["Eclesiastes 3:1", "Eclesiastes 12:13"], summary: "O Pregador reflete sobre o trabalho, o prazer, a sabedoria e conclui que o sentido da vida está em temer a Deus.", facts: ["Livro filosófico e reflexivo", "A palavra 'vaidade' aparece dezenas de vezes", "Citado por filósofos modernos"] },
  { id: "ct", name: "Cantares", testament: "old", author: "Tradicionalmente atribuído a Salomão", context: "Poema de amor entre o esposo e a esposa.", theme: "Amor conjugal e amor divino", purpose: "Celebrar o amor humano puro e, em sentido tipológico, o amor de Cristo pela Igreja.", teachings: ["O amor é dom de Deus", "A fidelidade é parte do amor", "O afeto é digno de celebração", "O amor é forte como a morte"], keyVerses: ["Cantares 2:4", "Cantares 8:6-7"], summary: "Poema lírico que celebra o amor entre o amado e a amada, refletindo também o amor de Deus por seu povo.", facts: ["Também chamado 'Cântico dos Cânticos'", "É lido na festa da Páscoa judaica", "Interpretado alegoricamente por séculos"] },
  { id: "is", name: "Isaías", testament: "old", author: "Isaías, filho de Amós", context: "Profetizou em Judá entre 740 e 680 a.C., durante o avanço assírio.", theme: "Juízo, salvação e o Messias", purpose: "Chamar Judá ao arrependimento e revelar o Messias salvador.", teachings: ["A salvação vem do Senhor", "Deus é santo e justo", "O Servo Sofredor leva os pecados", "Deus restaurará seu povo"], keyVerses: ["Isaías 6:8", "Isaías 9:6", "Isaías 53:5"], summary: "Anuncia juízo contra Judá e as nações e apresenta promessas messiânicas, incluindo o Servo Sofredor.", facts: ["Apresenta a profecia do Emanuel", "Capítulo 53 descreve a paixão de Cristo", "É o mais citado pelo Novo Testamento"] },
  { id: "jr", name: "Jeremias", testament: "old", author: "Jeremias", context: "Profetizou em Judá até a queda de Jerusalém em 586 a.C.", theme: "Juízo iminente e nova aliança", purpose: "Anunciar o juízo, chamar ao arrependimento e prometer a nova aliança.", teachings: ["Deus chama servos desde a juventude", "A idolatria traz juízo", "A esperança permanece no exílio", "Deus escreverá sua Lei nos corações"], keyVerses: ["Jeremias 29:11", "Jeremias 31:33"], summary: "Profecias de Jeremias contra Judá e as nações, junto a promessas de restauração e da nova aliança.", facts: ["Chamado 'profeta chorão'", "Viu a destruição de Jerusalém", "Ministrou por mais de 40 anos"] },
  { id: "lm", name: "Lamentações", testament: "old", author: "Tradicionalmente atribuído a Jeremias", context: "Escrito após a destruição de Jerusalém pelos babilônios.", theme: "Lamento e esperança", purpose: "Lamentar a destruição de Jerusalém e reafirmar a misericórdia de Deus.", teachings: ["O pecado tem consequências reais", "Há esperança mesmo no juízo", "As misericórdias do Senhor são novas a cada manhã", "O lamento é parte da fé"], keyVerses: ["Lamentações 3:22-23"], summary: "Cinco cânticos fúnebres pela queda de Jerusalém, com um clímax de esperança na fidelidade de Deus.", facts: ["Cada capítulo é um poema acróstico", "Lido na destruição do templo (Tisha B'Av)", "Centro do livro destaca a misericórdia"] },
  { id: "ez", name: "Ezequiel", testament: "old", author: "Ezequiel, o sacerdote", context: "Profetizou entre os exilados na Babilônia (593–571 a.C.).", theme: "Glória de Deus, juízo e restauração", purpose: "Mostrar a santidade de Deus, o juízo e a futura restauração do povo.", teachings: ["Deus é soberano sobre as nações", "A santidade exige arrependimento", "Deus restaurará Israel", "O coração de pedra será trocado por um de carne"], keyVerses: ["Ezequiel 36:26", "Ezequiel 37:14"], summary: "Visões de Ezequiel sobre a glória de Deus, o juízo de Jerusalém, a restauração futura e o vale de ossos secos.", facts: ["Visão dos seres viventes", "Vale de ossos secos vivificados", "Visão do novo templo"] },
  { id: "dn", name: "Daniel", testament: "old", author: "Daniel", context: "Ministério durante o exílio babilônico e o império persa.", theme: "Soberania de Deus sobre os impérios", purpose: "Mostrar que Deus reina sobre a história e revelar profecias do fim.", teachings: ["A integridade resiste à pressão", "Deus governa as nações", "A oração move o céu", "Os santos herdarão o reino"], keyVerses: ["Daniel 2:21", "Daniel 3:17-18", "Daniel 6:10"], summary: "Histórias de fidelidade na Babilônia e visões proféticas sobre o futuro dos reinos e a vinda do Reino de Deus.", facts: ["Inclui a cova dos leões", "Inclui a fornalha ardente", "Apresenta a profecia das 70 semanas"] },
  { id: "os", name: "Oséias", testament: "old", author: "Oséias", context: "Profetizou ao reino do Norte (Israel) antes de sua queda em 722 a.C.", theme: "Amor fiel de Deus e infidelidade do povo", purpose: "Ilustrar o amor de Deus por um povo infiel através do casamento do profeta.", teachings: ["Deus ama mesmo o infiel", "O pecado é adultério espiritual", "O arrependimento traz cura", "Deus deseja misericórdia, não sacrifício"], keyVerses: ["Oséias 6:6", "Oséias 14:4"], summary: "Oséias representa Deus, e Gômer, o povo infiel; mesmo assim, Deus chama Israel ao arrependimento e à restauração.", facts: ["Profeta menor mais autobiográfico", "Casamento simbólico com Gômer", "Citado por Jesus"] },
  { id: "jl", name: "Joel", testament: "old", author: "Joel, filho de Petuel", context: "Período provavelmente pré-exílico, após uma praga de gafanhotos em Judá.", theme: "Dia do Senhor e derramamento do Espírito", purpose: "Chamar ao arrependimento e profetizar o Espírito sobre toda carne.", teachings: ["O juízo precede a restauração", "Deus restaura os anos perdidos", "O Espírito virá sobre toda carne", "Ainda há tempo de voltar para o Senhor"], keyVerses: ["Joel 2:13", "Joel 2:28"], summary: "Usa a praga de gafanhotos como sinal do Dia do Senhor e anuncia o derramamento do Espírito Santo.", facts: ["Citado por Pedro em Atos 2", "Profetiza o Pentecostes", "Apenas 3 capítulos"] },
  { id: "am", name: "Amós", testament: "old", author: "Amós, pastor de Tecoa", context: "Profetizou no reino do Norte em meio à prosperidade e injustiça social.", theme: "Justiça social e juízo divino", purpose: "Denunciar a injustiça e a religiosidade vazia.", teachings: ["Deus odeia a injustiça", "Religião sem justiça é hipocrisia", "Deus julga as nações", "A misericórdia ainda é oferecida"], keyVerses: ["Amós 5:24"], summary: "Amós denuncia a opressão dos pobres, a corrupção e a falsa religiosidade de Israel, anunciando juízo.", facts: ["Pastor que se tornou profeta", "Profetizou cerca de 760 a.C.", "Forte ênfase em justiça social"] },
  { id: "ob", name: "Obadias", testament: "old", author: "Obadias", context: "Profecia contra Edom, descendente de Esaú, pela hostilidade contra Judá.", theme: "Juízo sobre Edom e restauração de Israel", purpose: "Anunciar a justiça de Deus contra os opressores de seu povo.", teachings: ["O orgulho precede a queda", "Deus julga os que oprimem seu povo", "O reino pertence ao Senhor", "Há esperança para Sião"], keyVerses: ["Obadias 1:15"], summary: "Curtíssimo livro que anuncia a destruição de Edom e a vitória final do povo de Deus.", facts: ["Livro mais curto do Antigo Testamento", "Tem apenas 21 versículos", "Trata da rivalidade Jacó/Esaú"] },
  { id: "jn", name: "Jonas", testament: "old", author: "Tradicionalmente atribuído a Jonas", context: "Profeta enviado a Nínive, capital da Assíria, no século VIII a.C.", theme: "Misericórdia de Deus às nações", purpose: "Mostrar que a misericórdia de Deus alcança até os inimigos.", teachings: ["Não se foge da presença de Deus", "Deus é compassivo com todos", "O arrependimento traz perdão", "Deus se importa com cada vida"], keyVerses: ["Jonas 2:9", "Jonas 4:11"], summary: "Jonas foge do chamado divino, é engolido por um grande peixe e, após arrepender-se, prega em Nínive, que se converte.", facts: ["Jesus comparou seu sinal ao de Jonas", "Nínive era inimiga de Israel", "Mostra o coração missionário de Deus"] },
  { id: "mq", name: "Miquéias", testament: "old", author: "Miquéias de Moresete", context: "Contemporâneo de Isaías, profetizou em Judá no século VIII a.C.", theme: "Justiça, misericórdia e o Messias", purpose: "Denunciar o pecado e prometer o governante que viria de Belém.", teachings: ["Deus exige justiça e misericórdia", "O Messias virá de Belém", "A religiosidade não substitui obediência", "Deus restaura o remanescente"], keyVerses: ["Miquéias 6:8", "Miquéias 5:2"], summary: "Denuncia a corrupção de líderes e profetas e anuncia o nascimento do Messias em Belém.", facts: ["Profetiza Belém como lugar do Messias", "Citado por sacerdotes em Mateus 2", "Forte ênfase ética"] },
  { id: "na", name: "Naum", testament: "old", author: "Naum, o elcosita", context: "Profecia contra Nínive, cerca de 100 anos após o arrependimento gerado por Jonas.", theme: "Juízo de Deus contra Nínive", purpose: "Anunciar a queda do império assírio como justiça divina.", teachings: ["Deus é lento em irar-se, mas justo", "O mal será julgado", "Há refúgio nos dias de angústia", "Nenhum império resiste a Deus"], keyVerses: ["Naum 1:7"], summary: "Profetiza a destruição de Nínive e a libertação de Judá do jugo assírio.", facts: ["Nínive caiu em 612 a.C.", "Contrasta com o livro de Jonas", "Apenas 3 capítulos"] },
  { id: "hc", name: "Habacuque", testament: "old", author: "Habacuque", context: "Profetizou em Judá pouco antes da invasão babilônica.", theme: "Fé em meio à injustiça", purpose: "Mostrar que o justo viverá pela fé, mesmo diante do mal.", teachings: ["É legítimo questionar a Deus", "Deus responde no seu tempo", "O justo vive pela fé", "A alegria está no Senhor"], keyVerses: ["Habacuque 2:4", "Habacuque 3:17-18"], summary: "Diálogo entre o profeta e Deus sobre a injustiça e a vinda do juízo, terminando em um cântico de fé.", facts: ["'O justo viverá pela fé' é citado três vezes no NT", "Diálogo entre profeta e Deus", "Encerra com hino de adoração"] },
  { id: "sf", name: "Sofonias", testament: "old", author: "Sofonias", context: "Profetizou em Judá durante o reinado de Josias.", theme: "Dia do Senhor e restauração", purpose: "Anunciar o juízo iminente e a restauração do remanescente.", teachings: ["O Dia do Senhor é certo", "Deus humilha os soberbos", "O remanescente será salvo", "Deus se alegra com seu povo"], keyVerses: ["Sofonias 3:17"], summary: "Anuncia juízo sobre Judá e as nações, encerrando com promessa de alegria e restauração para Sião.", facts: ["Descendente do rei Ezequias", "Profetizou junto a Jeremias", "Tem apenas 3 capítulos"] },
  { id: "ag", name: "Ageu", testament: "old", author: "Ageu", context: "Profetizou em 520 a.C., após o retorno do exílio, para incentivar a reconstrução do templo.", theme: "Prioridade da casa de Deus", purpose: "Repreender a apatia espiritual e motivar a reconstrução do templo.", teachings: ["Não buscar primeiro o reino de Deus traz frustração", "A obediência traz a presença de Deus", "Deus encoraja seus servos", "A glória futura será maior"], keyVerses: ["Ageu 1:7-8", "Ageu 2:9"], summary: "Mensagens curtas que motivam Zorobabel, Josué e o povo a reconstruir o templo de Jerusalém.", facts: ["Apenas 2 capítulos", "Contemporâneo de Zacarias", "Templo concluído em 516 a.C."] },
  { id: "zc", name: "Zacarias", testament: "old", author: "Zacarias, filho de Berequias", context: "Profetizou após o retorno do exílio, contemporâneo de Ageu.", theme: "Restauração e o Messias vindouro", purpose: "Encorajar o povo na reconstrução e revelar promessas messiânicas.", teachings: ["Deus zela por Jerusalém", "O Messias virá humilde e como Rei", "O Espírito é poderoso", "Deus reinará sobre toda a terra"], keyVerses: ["Zacarias 4:6", "Zacarias 9:9"], summary: "Visões e oráculos sobre a restauração de Jerusalém e a vinda do Messias, sofredor e glorioso.", facts: ["Profetiza Jesus entrando em Jerusalém", "Inclui visões noturnas", "Muito citado em Apocalipse"] },
  { id: "ml", name: "Malaquias", testament: "old", author: "Malaquias", context: "Último profeta do Antigo Testamento, cerca de 430 a.C.", theme: "Fidelidade e expectativa do Messias", purpose: "Repreender a frieza espiritual e anunciar o precursor do Messias.", teachings: ["Deus ama seu povo continuamente", "A negligência espiritual ofende a Deus", "Os dízimos refletem o coração", "Virá o sol da justiça"], keyVerses: ["Malaquias 3:10", "Malaquias 4:2"], summary: "Diálogos entre Deus e o povo repreendem hipocrisia, sacerdócio corrupto e anunciam a vinda do Messias.", facts: ["Último livro do AT", "Anuncia João Batista", "Encerra com a promessa do 'sol da justiça'"] },
  { id: "mt", name: "Mateus", testament: "new", author: "Mateus (Levi), apóstolo", context: "Escrito para leitores judeus, por volta de 50–70 d.C.", theme: "Jesus como o Rei Messias prometido", purpose: "Mostrar que Jesus é o Messias e Rei prometido pelo Antigo Testamento.", teachings: ["Jesus cumpre as profecias", "O Reino dos Céus está próximo", "A justiça do Reino supera a dos fariseus", "A grande comissão é discipular as nações"], keyVerses: ["Mateus 5:3-12", "Mateus 16:16", "Mateus 28:18-20"], summary: "Apresenta a vida, ensinos, morte e ressurreição de Jesus, enfatizando o cumprimento das profecias messiânicas.", facts: ["Contém o Sermão do Monte", "Genealogia inicial de Jesus", "Encerra com a Grande Comissão"] },
  { id: "mc", name: "Marcos", testament: "new", author: "João Marcos, discípulo de Pedro", context: "Provavelmente escrito em Roma, por volta de 55–65 d.C.", theme: "Jesus como o Servo Sofredor", purpose: "Apresentar Jesus como o Filho de Deus em ação e serviço.", teachings: ["Jesus veio para servir", "O discipulado exige negação", "A cruz é o centro da missão", "A fé é resposta ao reino"], keyVerses: ["Marcos 10:45"], summary: "Evangelho curto e dinâmico que enfatiza as ações de Jesus, seus milagres e seu caminho até a cruz.", facts: ["Evangelho mais curto", "Forte uso da palavra 'imediatamente'", "Marcos era companheiro de Pedro"] },
  { id: "lc", name: "Lucas", testament: "new", author: "Lucas, o médico amado", context: "Escrito a Teófilo, por volta de 60 d.C., após pesquisa cuidadosa.", theme: "Jesus como Salvador de todos", purpose: "Apresentar Jesus como o Salvador universal, especialmente dos perdidos.", teachings: ["Deus busca os perdidos", "A salvação é para judeus e gentios", "A oração é central na vida de Jesus", "O Espírito Santo capacita os servos"], keyVerses: ["Lucas 19:10", "Lucas 4:18-19"], summary: "Narra com detalhe histórico a vida de Jesus, suas parábolas de misericórdia e sua compaixão pelos marginalizados.", facts: ["Inclui as parábolas do filho pródigo e bom samaritano", "Único evangelho com a infância de Jesus em detalhe", "Lucas escreveu também Atos"] },
  { id: "jo", name: "João", testament: "new", author: "João, o apóstolo", context: "Escrito ao final do primeiro século, em Éfeso.", theme: "Jesus como o Filho de Deus", purpose: "Levar o leitor a crer que Jesus é o Cristo, Filho de Deus.", teachings: ["Jesus é o eterno Verbo", "A salvação se dá pela fé", "Jesus é o caminho, a verdade e a vida", "O Espírito guia em toda verdade"], keyVerses: ["João 1:1", "João 3:16", "João 14:6"], summary: "Apresenta sete sinais e sete declarações 'Eu sou' que revelam Jesus como o Filho de Deus encarnado.", facts: ["Contém o versículo mais conhecido (3:16)", "Sete sinais e sete 'Eu sou'", "Discurso do Cenáculo (caps. 13–17)"] },
  { id: "atos", name: "Atos", testament: "new", author: "Lucas", context: "Continuação do Evangelho de Lucas, cobre cerca de 30 anos após a ressurreição.", theme: "Expansão do evangelho pelo Espírito", purpose: "Narrar o crescimento da Igreja desde Jerusalém até Roma.", teachings: ["O Espírito Santo capacita testemunhas", "A Igreja é missionária", "O evangelho é para todas as nações", "Perseguição não detém o Reino"], keyVerses: ["Atos 1:8", "Atos 2:42"], summary: "Conta o Pentecostes, o crescimento da Igreja primitiva e as viagens missionárias de Pedro e Paulo.", facts: ["Inclui o Pentecostes", "Conversão de Saulo", "Termina com Paulo pregando em Roma"] },
  { id: "rm", name: "Romanos", testament: "new", author: "Paulo", context: "Escrito por volta de 57 d.C., à igreja em Roma.", theme: "Evangelho da graça e justificação pela fé", purpose: "Expor sistematicamente o evangelho da salvação pela fé.", teachings: ["Todos pecaram e necessitam de Cristo", "Justificação é pela fé, não pelas obras", "Há vida no Espírito", "Nada nos separa do amor de Deus"], keyVerses: ["Romanos 1:16-17", "Romanos 8:28", "Romanos 12:1-2"], summary: "Apresenta o problema do pecado, a solução em Cristo, a vida no Espírito e a aplicação prática do evangelho.", facts: ["Carta teológica mais densa de Paulo", "Influenciou a Reforma Protestante", "Capítulo 8 é um clássico cristão"] },
  { id: "1co", name: "1 Coríntios", testament: "new", author: "Paulo", context: "Escrito à igreja de Corinto, marcada por divisões e imoralidade.", theme: "Unidade, santidade e ordem na igreja", purpose: "Corrigir abusos, divisões e ensinar sobre vida cristã e dons.", teachings: ["A cruz é a sabedoria de Deus", "O corpo é templo do Espírito", "O amor é o caminho mais excelente", "A ressurreição é certa"], keyVerses: ["1 Coríntios 13:4-7", "1 Coríntios 15:58"], summary: "Trata de divisões, imoralidade, casamento, ceia, dons espirituais, amor (cap. 13) e ressurreição (cap. 15).", facts: ["Capítulo 13 é o 'hino do amor'", "Cap. 15 trata da ressurreição", "Aborda problemas práticos da igreja"] },
  { id: "2co", name: "2 Coríntios", testament: "new", author: "Paulo", context: "Carta mais pessoal, defendendo seu ministério apostólico.", theme: "Ministério, sofrimento e consolo", purpose: "Defender o ministério apostólico e ensinar sobre generosidade e sofrimento.", teachings: ["O poder se aperfeiçoa na fraqueza", "Somos embaixadores de Cristo", "A generosidade reflete a graça", "A nova criação está em Cristo"], keyVerses: ["2 Coríntios 5:17", "2 Coríntios 12:9"], summary: "Paulo defende seu ministério, fala sobre a contribuição para os santos e exalta a graça que sustenta na fraqueza.", facts: ["Carta mais pessoal de Paulo", "Fala de seu 'espinho na carne'", "Trata da coleta para os pobres"] },
  { id: "gl", name: "Gálatas", testament: "new", author: "Paulo", context: "Escrita às igrejas da Galácia, ameaçadas pelo legalismo judaizante.", theme: "Liberdade em Cristo e justificação pela fé", purpose: "Defender o evangelho da graça contra o legalismo.", teachings: ["A salvação é pela fé, não pela Lei", "Cristo nos libertou para a liberdade", "O fruto do Espírito caracteriza o cristão", "A cruz é nossa única glória"], keyVerses: ["Gálatas 2:20", "Gálatas 5:22-23"], summary: "Paulo refuta o legalismo, defende a justificação pela fé e ensina sobre o fruto do Espírito.", facts: ["Chamada 'manifesto da liberdade cristã'", "Influenciou Martinho Lutero", "Cap. 5 lista o fruto do Espírito"] },
  { id: "ef", name: "Efésios", testament: "new", author: "Paulo", context: "Carta da prisão, escrita por volta de 60 d.C.", theme: "A Igreja como corpo de Cristo", purpose: "Revelar as riquezas espirituais em Cristo e a unidade da Igreja.", teachings: ["Somos abençoados em Cristo", "A salvação é pela graça mediante a fé", "A unidade da Igreja é dom do Espírito", "É preciso revestir-se da armadura de Deus"], keyVerses: ["Efésios 2:8-9", "Efésios 6:10-11"], summary: "Apresenta as bênçãos espirituais em Cristo, a Igreja como seu corpo e a vida prática do cristão.", facts: ["Carta da prisão", "Cap. 6 fala da armadura espiritual", "Inclui ensino sobre casamento"] },
  { id: "fp", name: "Filipenses", testament: "new", author: "Paulo", context: "Carta de gratidão à amada igreja em Filipos, escrita na prisão.", theme: "Alegria em Cristo em toda circunstância", purpose: "Encorajar a igreja com alegria, humildade e união.", teachings: ["A verdadeira alegria está em Cristo", "Cristo nos chamou à humildade", "Tudo posso naquele que me fortalece", "A paz de Deus guarda o coração"], keyVerses: ["Filipenses 4:13", "Filipenses 4:6-7"], summary: "Carta cheia de alegria que exalta Cristo, a humildade, a comunhão e a paz que excede todo entendimento.", facts: ["Carta mais afetuosa de Paulo", "Cap. 2 contém o hino de Cristo", "Escrita na prisão"] },
  { id: "cl", name: "Colossenses", testament: "new", author: "Paulo", context: "Escrita para combater heresias que diminuíam a pessoa de Cristo.", theme: "Supremacia e suficiência de Cristo", purpose: "Mostrar que Cristo é supremo e suficiente para a vida cristã.", teachings: ["Cristo é a imagem do Deus invisível", "Nele habita toda plenitude", "A vida cristã é nova criação", "Tudo deve ser feito para a glória de Deus"], keyVerses: ["Colossenses 1:15-17", "Colossenses 3:1-2"], summary: "Exalta a supremacia de Cristo sobre toda criação e ensina a vida nova centrada nele.", facts: ["Apresenta Cristo como Criador", "Combate o gnosticismo incipiente", "Escrita na prisão"] },
  { id: "1ts", name: "1 Tessalonicenses", testament: "new", author: "Paulo", context: "Uma das primeiras cartas paulinas, escrita por volta de 50 d.C.", theme: "Esperança na volta de Cristo", purpose: "Encorajar os tessalonicenses na fé e ensinar sobre a volta do Senhor.", teachings: ["A vida cristã agrada a Deus", "Cristo voltará para buscar os seus", "Devemos vigiar e orar", "A santificação é vontade de Deus"], keyVerses: ["1 Tessalonicenses 4:16-17", "1 Tessalonicenses 5:16-18"], summary: "Encoraja a igreja em meio à perseguição e ensina sobre a vinda de Cristo e a vida santa.", facts: ["Cap. 4 fala do arrebatamento", "Carta muito pastoral", "Escrita pouco após a fundação da igreja"] },
  { id: "2ts", name: "2 Tessalonicenses", testament: "new", author: "Paulo", context: "Pouco depois da primeira carta, corrige equívocos sobre a volta de Cristo.", theme: "A vinda de Cristo e o homem da iniquidade", purpose: "Corrigir confusões sobre o Dia do Senhor e exortar à perseverança.", teachings: ["O Dia do Senhor virá no tempo certo", "É preciso firmeza diante do engano", "O trabalho honra a Cristo", "Deus julgará os perseguidores"], keyVerses: ["2 Tessalonicenses 3:3"], summary: "Esclarece que o Dia do Senhor não veio ainda e exorta o trabalho diligente e a firmeza na fé.", facts: ["Continua o ensino sobre escatologia", "Fala do 'homem da iniquidade'", "Repreende a ociosidade"] },
  { id: "1tm", name: "1 Timóteo", testament: "new", author: "Paulo", context: "Carta pastoral ao jovem Timóteo, líder em Éfeso.", theme: "Liderança e doutrina sã", purpose: "Orientar Timóteo na liderança da igreja e contra falsos mestres.", teachings: ["A sã doutrina deve ser preservada", "Líderes devem ser irrepreensíveis", "A piedade tem promessa para esta vida e a futura", "Cristo veio salvar pecadores"], keyVerses: ["1 Timóteo 1:15", "1 Timóteo 4:12"], summary: "Instruções sobre liderança, oração, doutrina, dinheiro e cuidado pastoral na igreja.", facts: ["Primeira carta pastoral", "Fala dos requisitos de bispos e diáconos", "Encoraja a juventude no ministério"] },
  { id: "2tm", name: "2 Timóteo", testament: "new", author: "Paulo", context: "Última carta de Paulo, escrita pouco antes de seu martírio.", theme: "Fidelidade no ministério até o fim", purpose: "Exortar Timóteo a permanecer fiel apesar da oposição.", teachings: ["A Palavra é inspirada e útil", "É preciso suportar aflições", "Combater o bom combate", "A coroa da justiça aguarda os fiéis"], keyVerses: ["2 Timóteo 3:16-17", "2 Timóteo 4:7"], summary: "Carta de despedida de Paulo, exortando fidelidade, sã doutrina e perseverança até o fim.", facts: ["Última carta paulina", "Texto clássico sobre inspiração da Bíblia", "Paulo aguardava o martírio"] },
  { id: "tt", name: "Tito", testament: "new", author: "Paulo", context: "Carta pastoral a Tito, líder da igreja em Creta.", theme: "Ordem, doutrina e boas obras", purpose: "Instruir Tito a organizar igrejas e ensinar a sã doutrina.", teachings: ["Líderes devem ter caráter", "A graça ensina a viver com piedade", "Boas obras seguem a salvação", "É preciso evitar contendas vãs"], keyVerses: ["Tito 2:11-12", "Tito 3:5"], summary: "Orientações sobre presbíteros, conduta cristã e a graça salvadora de Deus.", facts: ["Carta pastoral curta", "Ênfase em 'boas obras'", "Endereçada a Creta"] },
  { id: "fm", name: "Filemom", testament: "new", author: "Paulo", context: "Carta pessoal sobre Onésimo, escravo fugitivo convertido.", theme: "Perdão e reconciliação em Cristo", purpose: "Pedir a Filemom que receba Onésimo como irmão.", teachings: ["Em Cristo somos iguais", "O perdão restaura relações", "O evangelho transforma estruturas", "O amor cristão é prático"], keyVerses: ["Filemom 1:6"], summary: "Carta breve onde Paulo intercede pelo escravo Onésimo, agora irmão em Cristo.", facts: ["Carta mais curta de Paulo", "Toca em escravidão sutilmente", "Carta da prisão"] },
  { id: "hb", name: "Hebreus", testament: "new", author: "Autor desconhecido", context: "Escrita a cristãos de origem judaica tentados a voltar ao judaísmo.", theme: "Superioridade de Cristo", purpose: "Mostrar que Cristo é superior aos profetas, anjos, Moisés e ao sacerdócio levítico.", teachings: ["Cristo é o sumo sacerdote perfeito", "Sua obra é definitiva", "É preciso perseverar na fé", "Sem fé é impossível agradar a Deus"], keyVerses: ["Hebreus 4:12", "Hebreus 11:1", "Hebreus 12:1-2"], summary: "Exalta Cristo como cumprimento e superior ao Antigo Pacto e exorta à perseverança na fé.", facts: ["Cap. 11 é a 'galeria da fé'", "Compara Cristo ao sacerdócio levítico", "Autor permanece desconhecido"] },
  { id: "tg", name: "Tiago", testament: "new", author: "Tiago, irmão do Senhor", context: "Carta às doze tribos da dispersão, prática e ética.", theme: "Fé que se mostra em obras", purpose: "Mostrar que a fé verdadeira se manifesta em ações concretas.", teachings: ["A fé sem obras é morta", "A língua precisa ser dominada", "Deus dá graça aos humildes", "A oração do justo é eficaz"], keyVerses: ["Tiago 1:22", "Tiago 2:17"], summary: "Carta prática sobre fé, ações, língua, sabedoria, paciência e oração.", facts: ["Carta mais ética do NT", "Compara-se aos Provérbios", "Escrita por um irmão de Jesus"] },
  { id: "1pe", name: "1 Pedro", testament: "new", author: "Pedro, apóstolo", context: "Escrita a cristãos espalhados sofrendo perseguição.", theme: "Esperança em meio ao sofrimento", purpose: "Encorajar cristãos a perseverarem sob perseguição com esperança viva.", teachings: ["Somos peregrinos com herança viva", "O sofrimento purifica a fé", "Somos sacerdócio real", "É preciso resistir ao diabo firmes"], keyVerses: ["1 Pedro 1:3", "1 Pedro 5:7"], summary: "Encoraja cristãos perseguidos a viverem com santidade, submissão e esperança em Cristo.", facts: ["Tema central: sofrimento", "Cita muito o AT", "Carta circular"] },
  { id: "2pe", name: "2 Pedro", testament: "new", author: "Pedro, apóstolo", context: "Última carta de Pedro, antes de seu martírio.", theme: "Conhecimento de Cristo e alerta contra falsos mestres", purpose: "Advertir contra falsos mestres e exortar ao crescimento espiritual.", teachings: ["O conhecimento de Cristo nos fortalece", "A Palavra é mais segura que visões", "Falsos mestres serão julgados", "O Dia do Senhor virá como ladrão"], keyVerses: ["2 Pedro 1:3", "2 Pedro 3:9"], summary: "Exorta ao crescimento na graça, denuncia falsos mestres e anuncia novos céus e nova terra.", facts: ["Última carta de Pedro", "Reconhece as cartas de Paulo como Escritura", "Cap. 3 fala dos novos céus"] },
  { id: "1jo", name: "1 João", testament: "new", author: "João, o apóstolo", context: "Escrita para combater heresias e confirmar a fé.", theme: "Comunhão com Deus e amor fraternal", purpose: "Dar segurança aos crentes sobre sua salvação e exortá-los ao amor.", teachings: ["Deus é luz e amor", "Quem ama nasceu de Deus", "Devemos confessar nossos pecados", "A vitória vem pela fé"], keyVerses: ["1 João 1:9", "1 João 4:8", "1 João 5:13"], summary: "Carta que enfatiza amor, verdade, comunhão e segurança da vida eterna em Cristo.", facts: ["Repete a palavra 'amor' muitas vezes", "Combate o gnosticismo", "Oferece testes da fé verdadeira"] },
  { id: "2jo", name: "2 João", testament: "new", author: "João, o apóstolo", context: "Carta breve à 'senhora eleita' e seus filhos.", theme: "Andar em amor e verdade", purpose: "Exortar à verdade e advertir contra falsos mestres.", teachings: ["Amor e verdade andam juntos", "Falsos mestres não devem ser acolhidos", "Permanecer na doutrina de Cristo é vital"], keyVerses: ["2 João 1:6"], summary: "Curtíssima carta que une amor, verdade e cuidado doutrinário.", facts: ["Tem apenas 13 versículos", "Endereçada à 'senhora eleita'", "Carta pastoral pessoal"] },
  { id: "3jo", name: "3 João", testament: "new", author: "João, o apóstolo", context: "Carta pessoal a Gaio, sobre hospitalidade e liderança.", theme: "Hospitalidade e fidelidade", purpose: "Elogiar Gaio, repreender Diótrefes e recomendar Demétrio.", teachings: ["A hospitalidade é serviço a Cristo", "O orgulho destrói o ministério", "Andar na verdade traz alegria"], keyVerses: ["3 João 1:4"], summary: "Carta pessoal que valoriza a hospitalidade cristã e adverte contra líderes arrogantes.", facts: ["Carta mais curta do NT em palavras gregas", "Menciona Gaio, Diótrefes e Demétrio", "Tem apenas 14 versículos"] },
  { id: "jd", name: "Judas", testament: "new", author: "Judas, irmão de Tiago", context: "Carta breve que combate falsos mestres infiltrados na igreja.", theme: "Contender pela fé", purpose: "Exortar os crentes a defender a fé entregue aos santos.", teachings: ["É preciso lutar pela fé", "Falsos mestres serão julgados", "Edificar-se na santíssima fé", "Deus é poderoso para nos guardar"], keyVerses: ["Judas 1:3", "Judas 1:24-25"], summary: "Adverte contra a apostasia e exorta à perseverança e à edificação na fé.", facts: ["Cita livros não canônicos", "Apenas um capítulo", "Doxologia final muito conhecida"] },
  { id: "ap", name: "Apocalipse", testament: "new", author: "João, o apóstolo", context: "Escrito na ilha de Patmos, por volta de 95 d.C., durante perseguição romana.", theme: "Vitória final de Cristo", purpose: "Revelar Jesus Cristo glorificado e a consumação do plano de Deus.", teachings: ["Cristo reina sobre a história", "A Igreja perseverará", "O mal será derrotado", "Haverá novos céus e nova terra"], keyVerses: ["Apocalipse 1:8", "Apocalipse 21:4"], summary: "Visões proféticas sobre as sete igrejas, juízos finais, queda do mal e a nova Jerusalém com Cristo reinante.", facts: ["Último livro da Bíblia", "Rico em simbolismos", "Encerra com a promessa 'Eis que venho sem demora'"] },
];

export function getResumoById(id: string): ResumoBiblico | undefined {
  return resumosBiblicos.find((r) => r.id === id);
}

export function searchResumos(query: string): ResumoBiblico[] {
  const q = query.trim().toLowerCase();
  if (!q) return resumosBiblicos;
  return resumosBiblicos.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      r.theme.toLowerCase().includes(q) ||
      r.author.toLowerCase().includes(q) ||
      r.summary.toLowerCase().includes(q),
  );
}