/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as DevocionalRouteImport } from './routes/devocional'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HarpaIndexRouteImport } from './routes/harpa.index'
import { Route as BibliaIndexRouteImport } from './routes/biblia.index'
import { Route as HarpaIdRouteImport } from './routes/harpa.$id'
import { Route as BibliaBookChapterRouteImport } from './routes/biblia.$book.$chapter'

const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionalRoute = DevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarpaIndexRoute = HarpaIndexRouteImport.update({
  id: '/harpa/',
  path: '/harpa/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaIndexRoute = BibliaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaRoute,
} as any)
const HarpaIdRoute = HarpaIdRouteImport.update({
  id: '/harpa/$id',
  path: '/harpa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaBookChapterRoute = BibliaBookChapterRouteImport.update({
  id: '/$book/$chapter',
  path: '/$book/$chapter',
  getParentRoute: () => BibliaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/busca': typeof BuscaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/devocional': typeof DevocionalRoute
  '/favoritos': typeof FavoritosRoute
  '/harpa/$id': typeof HarpaIdRoute
  '/biblia/': typeof BibliaIndexRoute
  '/harpa/': typeof HarpaIndexRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/busca': typeof BuscaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/devocional': typeof DevocionalRoute
  '/favoritos': typeof FavoritosRoute
  '/harpa/$id': typeof HarpaIdRoute
  '/biblia': typeof BibliaIndexRoute
  '/harpa': typeof HarpaIndexRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/busca': typeof BuscaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/devocional': typeof DevocionalRoute
  '/favoritos': typeof FavoritosRoute
  '/harpa/$id': typeof HarpaIdRoute
  '/biblia/': typeof BibliaIndexRoute
  '/harpa/': typeof HarpaIndexRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotacoes'
    | '/biblia'
    | '/busca'
    | '/configuracoes'
    | '/devocional'
    | '/favoritos'
    | '/harpa/$id'
    | '/biblia/'
    | '/harpa/'
    | '/biblia/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotacoes'
    | '/busca'
    | '/configuracoes'
    | '/devocional'
    | '/favoritos'
    | '/harpa/$id'
    | '/biblia'
    | '/harpa'
    | '/biblia/$book/$chapter'
  id:
    | '__root__'
    | '/'
    | '/anotacoes'
    | '/biblia'
    | '/busca'
    | '/configuracoes'
    | '/devocional'
    | '/favoritos'
    | '/harpa/$id'
    | '/biblia/'
    | '/harpa/'
    | '/biblia/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotacoesRoute: typeof AnotacoesRoute
  BibliaRoute: typeof BibliaRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DevocionalRoute: typeof DevocionalRoute
  FavoritosRoute: typeof FavoritosRoute
  HarpaIdRoute: typeof HarpaIdRoute
  HarpaIndexRoute: typeof HarpaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocional': {
      id: '/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof DevocionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harpa/': {
      id: '/harpa/'
      path: '/harpa'
      fullPath: '/harpa/'
      preLoaderRoute: typeof HarpaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/': {
      id: '/biblia/'
      path: '/'
      fullPath: '/biblia/'
      preLoaderRoute: typeof BibliaIndexRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/harpa/$id': {
      id: '/harpa/$id'
      path: '/harpa/$id'
      fullPath: '/harpa/$id'
      preLoaderRoute: typeof HarpaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$book/$chapter': {
      id: '/biblia/$book/$chapter'
      path: '/$book/$chapter'
      fullPath: '/biblia/$book/$chapter'
      preLoaderRoute: typeof BibliaBookChapterRouteImport
      parentRoute: typeof BibliaRoute
    }
  }
}

interface BibliaRouteChildren {
  BibliaIndexRoute: typeof BibliaIndexRoute
  BibliaBookChapterRoute: typeof BibliaBookChapterRoute
}

const BibliaRouteChildren: BibliaRouteChildren = {
  BibliaIndexRoute: BibliaIndexRoute,
  BibliaBookChapterRoute: BibliaBookChapterRoute,
}

const BibliaRouteWithChildren =
  BibliaRoute._addFileChildren(BibliaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotacoesRoute: AnotacoesRoute,
  BibliaRoute: BibliaRouteWithChildren,
  BuscaRoute: BuscaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DevocionalRoute: DevocionalRoute,
  FavoritosRoute: FavoritosRoute,
  HarpaIdRoute: HarpaIdRoute,
  HarpaIndexRoute: HarpaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
