/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HarpaRouteImport } from './routes/harpa'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EstudosRouteImport } from './routes/estudos'
import { Route as DevocionalRouteImport } from './routes/devocional'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HarpaIndexRouteImport } from './routes/harpa.index'
import { Route as BibliaIndexRouteImport } from './routes/biblia.index'
import { Route as HarpaIdRouteImport } from './routes/harpa.$id'
import { Route as EstudosIdRouteImport } from './routes/estudos.$id'
import { Route as BibliaBookRouteImport } from './routes/biblia.$book'
import { Route as BibliaBookIndexRouteImport } from './routes/biblia.$book.index'
import { Route as BibliaBookChapterRouteImport } from './routes/biblia.$book.$chapter'

const HarpaRoute = HarpaRouteImport.update({
  id: '/harpa',
  path: '/harpa',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosRoute = EstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionalRoute = DevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarpaIndexRoute = HarpaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HarpaRoute,
} as any)
const BibliaIndexRoute = BibliaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaRoute,
} as any)
const HarpaIdRoute = HarpaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HarpaRoute,
} as any)
const EstudosIdRoute = EstudosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EstudosRoute,
} as any)
const BibliaBookRoute = BibliaBookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => BibliaRoute,
} as any)
const BibliaBookIndexRoute = BibliaBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaBookRoute,
} as any)
const BibliaBookChapterRoute = BibliaBookChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => BibliaBookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/busca': typeof BuscaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/devocional': typeof DevocionalRoute
  '/estudos': typeof EstudosRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/harpa': typeof HarpaRouteWithChildren
  '/biblia/$book': typeof BibliaBookRouteWithChildren
  '/estudos/$id': typeof EstudosIdRoute
  '/harpa/$id': typeof HarpaIdRoute
  '/biblia/': typeof BibliaIndexRoute
  '/harpa/': typeof HarpaIndexRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterRoute
  '/biblia/$book/': typeof BibliaBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/busca': typeof BuscaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/devocional': typeof DevocionalRoute
  '/estudos': typeof EstudosRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/estudos/$id': typeof EstudosIdRoute
  '/harpa/$id': typeof HarpaIdRoute
  '/biblia': typeof BibliaIndexRoute
  '/harpa': typeof HarpaIndexRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterRoute
  '/biblia/$book': typeof BibliaBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/busca': typeof BuscaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/devocional': typeof DevocionalRoute
  '/estudos': typeof EstudosRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/harpa': typeof HarpaRouteWithChildren
  '/biblia/$book': typeof BibliaBookRouteWithChildren
  '/estudos/$id': typeof EstudosIdRoute
  '/harpa/$id': typeof HarpaIdRoute
  '/biblia/': typeof BibliaIndexRoute
  '/harpa/': typeof HarpaIndexRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterRoute
  '/biblia/$book/': typeof BibliaBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotacoes'
    | '/biblia'
    | '/busca'
    | '/configuracoes'
    | '/devocional'
    | '/estudos'
    | '/favoritos'
    | '/harpa'
    | '/biblia/$book'
    | '/estudos/$id'
    | '/harpa/$id'
    | '/biblia/'
    | '/harpa/'
    | '/biblia/$book/$chapter'
    | '/biblia/$book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotacoes'
    | '/busca'
    | '/configuracoes'
    | '/devocional'
    | '/estudos'
    | '/favoritos'
    | '/estudos/$id'
    | '/harpa/$id'
    | '/biblia'
    | '/harpa'
    | '/biblia/$book/$chapter'
    | '/biblia/$book'
  id:
    | '__root__'
    | '/'
    | '/anotacoes'
    | '/biblia'
    | '/busca'
    | '/configuracoes'
    | '/devocional'
    | '/estudos'
    | '/favoritos'
    | '/harpa'
    | '/biblia/$book'
    | '/estudos/$id'
    | '/harpa/$id'
    | '/biblia/'
    | '/harpa/'
    | '/biblia/$book/$chapter'
    | '/biblia/$book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotacoesRoute: typeof AnotacoesRoute
  BibliaRoute: typeof BibliaRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DevocionalRoute: typeof DevocionalRoute
  EstudosRoute: typeof EstudosRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  HarpaRoute: typeof HarpaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/harpa': {
      id: '/harpa'
      path: '/harpa'
      fullPath: '/harpa'
      preLoaderRoute: typeof HarpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos': {
      id: '/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof EstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocional': {
      id: '/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof DevocionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harpa/': {
      id: '/harpa/'
      path: '/'
      fullPath: '/harpa/'
      preLoaderRoute: typeof HarpaIndexRouteImport
      parentRoute: typeof HarpaRoute
    }
    '/biblia/': {
      id: '/biblia/'
      path: '/'
      fullPath: '/biblia/'
      preLoaderRoute: typeof BibliaIndexRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/harpa/$id': {
      id: '/harpa/$id'
      path: '/$id'
      fullPath: '/harpa/$id'
      preLoaderRoute: typeof HarpaIdRouteImport
      parentRoute: typeof HarpaRoute
    }
    '/estudos/$id': {
      id: '/estudos/$id'
      path: '/$id'
      fullPath: '/estudos/$id'
      preLoaderRoute: typeof EstudosIdRouteImport
      parentRoute: typeof EstudosRoute
    }
    '/biblia/$book': {
      id: '/biblia/$book'
      path: '/$book'
      fullPath: '/biblia/$book'
      preLoaderRoute: typeof BibliaBookRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/biblia/$book/': {
      id: '/biblia/$book/'
      path: '/'
      fullPath: '/biblia/$book/'
      preLoaderRoute: typeof BibliaBookIndexRouteImport
      parentRoute: typeof BibliaBookRoute
    }
    '/biblia/$book/$chapter': {
      id: '/biblia/$book/$chapter'
      path: '/$chapter'
      fullPath: '/biblia/$book/$chapter'
      preLoaderRoute: typeof BibliaBookChapterRouteImport
      parentRoute: typeof BibliaBookRoute
    }
  }
}

interface BibliaBookRouteChildren {
  BibliaBookChapterRoute: typeof BibliaBookChapterRoute
  BibliaBookIndexRoute: typeof BibliaBookIndexRoute
}

const BibliaBookRouteChildren: BibliaBookRouteChildren = {
  BibliaBookChapterRoute: BibliaBookChapterRoute,
  BibliaBookIndexRoute: BibliaBookIndexRoute,
}

const BibliaBookRouteWithChildren = BibliaBookRoute._addFileChildren(
  BibliaBookRouteChildren,
)

interface BibliaRouteChildren {
  BibliaBookRoute: typeof BibliaBookRouteWithChildren
  BibliaIndexRoute: typeof BibliaIndexRoute
}

const BibliaRouteChildren: BibliaRouteChildren = {
  BibliaBookRoute: BibliaBookRouteWithChildren,
  BibliaIndexRoute: BibliaIndexRoute,
}

const BibliaRouteWithChildren =
  BibliaRoute._addFileChildren(BibliaRouteChildren)

interface EstudosRouteChildren {
  EstudosIdRoute: typeof EstudosIdRoute
}

const EstudosRouteChildren: EstudosRouteChildren = {
  EstudosIdRoute: EstudosIdRoute,
}

const EstudosRouteWithChildren =
  EstudosRoute._addFileChildren(EstudosRouteChildren)

interface HarpaRouteChildren {
  HarpaIdRoute: typeof HarpaIdRoute
  HarpaIndexRoute: typeof HarpaIndexRoute
}

const HarpaRouteChildren: HarpaRouteChildren = {
  HarpaIdRoute: HarpaIdRoute,
  HarpaIndexRoute: HarpaIndexRoute,
}

const HarpaRouteWithChildren = HarpaRoute._addFileChildren(HarpaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotacoesRoute: AnotacoesRoute,
  BibliaRoute: BibliaRouteWithChildren,
  BuscaRoute: BuscaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DevocionalRoute: DevocionalRoute,
  EstudosRoute: EstudosRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  HarpaRoute: HarpaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
